### ISSUE TITLE
enable TLS，presigned url error  NoSuchBucket

### ISSUE THREAD

**Issue by 18506711722** [rustfs/rustfs#1099]
https://github.com/rustfs/rustfs/issues/1083

RUSTFS_SERVER_DOMAINS：fs.aion0573.top
RUSTFS_TLS_PATH：/opt/tls

https:// [user.fs.aion0573.top:19000/avatar-admin-1765281812109.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20251209T140816Z&X-Amz-SignedHeaders=host&X-Amz-Credential=7aNABSVq83DPZJzn1fEw%2F20251209%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=d076eabd3c647ed83461442b141d8175f122308c29bf9e446d9bb20b98568b3b](https://user.fs.aion0573.top:19000/avatar-admin-1765281812109.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20251209T140816Z&X-Amz-SignedHeaders=host&X-Amz-Credential=7aNABSVq83DPZJzn1fEw%2F20251209%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Expires=1800&X-Amz-Signature=d076eabd3c647ed83461442b141d8175f122308c29bf9e446d9bb20b98568b3b)

NoSuchBucket未找到音量

**Comment by 18506711722** [comment]
I encountered obstacles when using rustfs and hope to get help as soon as possible

**Comment by 18506711722** [comment]
I feel that this problem is not an isolated case and still hope it can be solved

**Comment by loverustfs** [comment]
Don't worry, we'll fix it.

**Comment by 18506711722** [comment]
Thank you in advance to the open source team

**Comment by 0xdx2** [comment]
@18506711722 We've identified the issue and will have it resolved shortly. Thank you for waiting.

**Comment by 0xdx2** [comment]
We have fixed and tested it. Please wait patiently for the update before trying again.

<img width="1856" height="626" alt="Image" src="https://github.com/user-attachments/assets/54c16586-1c82-49a6-a03b-b8eb9077bb6f" />

> We didn't configure TLS for test.**.com, only for **.com, so the download is like this.

**Comment by 18506711722** [comment]
I'm not familiar with the s3 standard, but I still have a suggestion to say: Is it more friendly to deploy FS to show the tube parameters in the preview link in the form of paths or parameters? Because generic domain SSL is often more expensive than domain SSL.

**Comment by loverustfs** [comment]
Hey @18506711722 ,

Thank you for using RustFS.

This bug has been fixed. Please upgrade to the latest version, alpha.75: https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.75

Please verify that this resolves the issue. If the problem persists, please leave a comment below and we will reopen this issue.

**Comment by 18506711722** [comment]
For an excellent project, I will immediately test whether the functions have been fixed

**Comment by 18506711722** [comment]
> 嘿，
> 
> 感谢你使用RustFS。
> 
> 该漏洞已被修复。请升级到最新版本 alpha.75：https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.75
> 
> 请确认此举已解决问题。如果问题依旧，请在下方留言，我们将重新开放此问题。

Will docker images release updates synchronously?  I'm using version 1.0.0-alpha.76, but it seems the problem hasn't been fixed?

**Comment by loverustfs** [comment]
Yes, push notifications failed with alpha.75. You can try alpha.76.

**Comment by 18506711722** [comment]
alpha.76 
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
</Error>

The problem remained unsolved

**Comment by loverustfs** [comment]
Hey @0xdx2 ,

This bug has not been fixed according to user feedback.

**Comment by 0xdx2** [comment]
@18506711722 I send an application 2 u on wechat by the mobile number, pls accept.

**Comment by loverustfs** [comment]
Hey @18506711722 ,

This bug has been fixed. Please upgrade to the latest version, alpha.77: https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.77

We will close this issue for now. If the problem persists, please leave a comment and we will reopen it to continue tracking.

**Comment by fullaware** [comment]
@loverustfs Unfortunately I still have an issue with alpha.77 I'm still getting NoSuchBucket for http://servername.subdomain.domain.com:9001, issue doesn't occur when I hit the server via IP address.

**Comment by 0xdx2** [comment]
> @loverustfs Unfortunately I still have an issue with alpha.77 I'm still getting NoSuchBucket for http://servername.subdomain.domain.com:9001, issue doesn't occur when I hit the server via IP address.

port of console and port of api must be configured both as RUSTFS_SERVER_DOMAINS which split by Comma.
