### ISSUE TITLE
Can't login to docker deployment.

### ISSUE THREAD

**Issue by pdavis68** [rustfs/rustfs#123]
**Describe the bug**
Other than changing the ports, I deployed it as per the instructions (my port 9000 was already being used)

`docker run -d -p 9090:9000 -p 9091:9001 -v /data:/data quay.io/rustfs/rustfs`

The machine it's running on is locally known on the network simply as 'server'.

I go to: `http://server:9091/auth/login`

I put `rustfsadmin` as the account and key for the "Key Login". I assume that's what I should do. The instructions are a bit ambiguous since they don't mention the Key Login vs STS Login.

But when I login it gives me "Login Failed". I opened dev tools and there appears to be a CORS error on the POST to http://server:9090/ when you press the Login button. 

**To Reproduce**
1. `docker run -d -p 9090:9000 -p 9091:9001 -v /data:/data quay.io/rustfs/rustfs`
2. browse `http://server:9091/auth/login`
3. login.

**Expected behavior**
To login without a CORS error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 137.0.7151.68

**Comment by loverustfs** [comment]
@pdavis68 

We are very sorry!
We are urgently adjusting the release package, please wait.

**Comment by pdavis68** [comment]
Thanks for the quick update!

**Comment by loverustfs** [comment]
> Thanks for the quick update!

Sorry for the inconvenience. We have encountered some issues in order to resolve the issue of docker forwarding ports.

**Comment by loverustfs** [comment]
@pdavis68 New docker image is being generated. We will notify you when they are ready.

**Comment by loverustfs** [comment]
Hi @pdavis68 ,

Our new docker image is ready. Do you see any errors when using it?

If you have any questions, please feel free to reply to us.

**Comment by pdavis68** [comment]
I'm still getting the same problem.

https://quay.io/repository/rustfs/rustfs?tab=tags&tag=latest

Says that it was last updated 12 hours ago. Is that the wrong image?

**Comment by loverustfs** [comment]
> I'm still getting the same problem.
> 
> https://quay.io/repository/rustfs/rustfs?tab=tags&tag=latest
> 
> Says that it was last updated 12 hours ago. Is that the wrong image?

Yes, the latest docker image fixes some bugs.

The automatic pipeline has also encountered some errors that are being resolved.

**Comment by loverustfs** [comment]
Hi @pdavis68 ,
This bug is fixed, please check it.

**Comment by pdavis68** [comment]
Not fixed. Just a different error now.

"Login failed, please check server configuration"

This is the value of api in the s3 config.    "baseURL": "http://server:9090:9000/rustfs/admin/v3"

This is how i'm running it.

`sudo docker run -d -p 9090:9000 -p 9091:9001 -v /data:/data quay.io/rustfs/rustfs`
