### ISSUE TITLE
IpAddress aws:SourceIp   Not effective

### ISSUE THREAD

**Issue by yangguangjin** [rustfs/rustfs#1301]
My configuration is as above, with IP restrictions enabled. However, I cannot access it using 192.168.0.10. Is this due to the internal network IP? Does it not support internal network segments?

I want to create a public bucket accessible only from the internal IP address of my frontend. All user requests to my frontend will be routed through the frontend to request RustFS. This is to prevent link hijacking.

While Referer headers could be used, they can be forged. Therefore, I want to add IP restrictions as well.

Is there a way to achieve this?

```
{
"ID": "",
"Version": "2012-10-17",
"Statement": [
{
"Sid": "",
"Effect": "Allow",
"Principal": {
"AWS": [
""
]
},
"Action": [
"s3:GetObject"
],
"NotAction": [],
"Resource": [
"arn:aws:s3:::static/"
],
"NotResource": [],
"Condition": {
"IpAddress": {
"aws:SourceIp": [
"192.168.0.0/16",
"192.169.0.10/32"
]
}
},
{
"Sid": "",
"Effect": "Allow",
"Principal": {
"AWS": [
"arn:aws:iam:::root"
]
},
"Action": [
"s3:DeleteObject",
"s3:PutObject",
"s3:PutObjectTagging",
"s3:DeleteObjectTagging"
],
"NotAction": [],
"Resource": [
"arn:aws:s3:::static/"
],
"NotResource": [],
"Condition": {}
}
]
}



```

**Comment by yangguangjin** [comment]
use Latest Version

**Comment by yangguangjin** [comment]
I was able to access it using the following configuration.
Is this because all devices on my local network share the same public IP address?

“aws:SourceIp”: [
“127.0.0.1/32”
]

**Comment by loverustfs** [comment]
Hello @yangguangjin ,

This feature has been completed, plz wait for next version release.

https://github.com/rustfs/rustfs/pull/1306

**Comment by loverustfs** [comment]
Hello @yangguangjin ,


This release fixes the bug and addresses the issue you reported.

To help keep our issue tracker organized, we are closing this issue for now. However, if you verify the fix and find that the problem persists, please leave a comment and we will reopen it.

Latest alpha.78 release: https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.78

**Comment by yangguangjin** [comment]
The issue persists. This time, 127.0.0.1/32 doesn't work either, whereas it was functional in the previous version.

<img width="1751" height="818" alt="Image" src="https://github.com/user-attachments/assets/36625573-d4bb-4c37-8de5-a63c046fe7b6" />

<img width="827" height="643" alt="Image" src="https://github.com/user-attachments/assets/4c9bc16f-bdd4-4bac-b9cf-3cf1de1dc537" />

**Comment by loverustfs** [comment]
Ok, i reopened this issue.

**Comment by loverustfs** [comment]
Hello @yangguangjin ,

This bug has been fixed.

**Comment by loverustfs** [comment]
We have just released the latest version of RustFS. We believe this update fixes the bug you reported.

Please give it a try. If the issue persists, let us know in the comments. If it is resolved, please feel free to close this issue.

Release link: https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.79

**Comment by comdude2** [comment]
This doesn't appear to have fixed the issue for me. I've updated to 1.0.0-alpha.79 and the aws:SourceIP condition still doesn't seem to work. I've deployed RustFS via TrueNAS (docker). Removing the IP constraint allows access to the resource.

I've tried binding to host network etc to ensure it's not a docker on TrueNAS issue, no joy.

**Comment by loverustfs** [comment]
> This doesn't appear to have fixed the issue for me. I've updated to 1.0.0-alpha.79 and the aws:SourceIP condition still doesn't seem to work. I've deployed RustFS via TrueNAS (docker). Removing the IP constraint allows access to the resource.
> 
> I've tried binding to host network etc to ensure it's not a docker on TrueNAS issue, no joy.

Ok, we'll check it.

**Comment by LeonWang0735** [comment]
Thanks for the feedback.
From what we’ve seen so far, the aws:SourceIp condition itself is working as expected. However, it is evaluated against the actual source IP address seen by RustFS, not the client’s original IP.
To help us pinpoint the issue, could you please provide the following details:
- How requests reach RustFS:
>browser → RustFS directly
>browser → frontend → RustFS (proxy)
- RustFS network setup:
listening address
- docker network mode
- Are the frontend and RustFS deployed on the same machine?


Any additional details you consider important would also be helpful.
Thanks for your patience — this information will help us narrow it down quickly.
@comdude2

**Comment by loverustfs** [comment]
Inactive, close.
