### ISSUE TITLE
Based on the docker installation, the running permissions are insufficient and cannot be carried out.

### ISSUE THREAD

**Issue by WangNingkai** [rustfs/rustfs#22]
<img width="1210" alt="Image" src="https://github.com/user-attachments/assets/a0afe80d-29a0-44e8-96ec-4e3ce65dfaf5" />

**Comment by WangNingkai** [comment]
In addition, I would like to ask where is the demo account?

**Comment by loverustfs** [comment]
Yes, we are working on fixing this.

You can try using this image first.
`podman run -d -p 9000:9000 -p 9001:9001 -v /data:/data quay.io/rustfs/rustfs
`
Don't put this docker into production yet.

**Comment by houseme** [comment]
> In addition, I would like to ask where is the demo account?

default: `rustfsadmin`/`rustfsadmin` 
visit: `http://localshot:9001`

**Comment by loverustfs** [comment]
If you have a successful startup, you are also welcome to evaluate and compare our speed with other object storage products.

https://github.com/user-attachments/assets/2e4979b5-260c-4f2c-ac12-c87fd558072a

**Comment by loverustfs** [comment]
`curl -O  https://rustfs.com/install_rustfs.sh && bash install_rustfs.sh
`
Please try it.

**Comment by loverustfs** [comment]
```
 docker run -d -p 9000:9000 -p 9001:9001 -v /data:/data rustfs/rustfs
podman run -d -p 9000:9000 -p 9001:9001 -v /data:/data quay.io/rustfs/rustfs


```
This issue has been fixed and we will close it in 24 hours if you don't have new issues.

**Comment by biociao** [comment]
By using `docker run -d -p 5000:9000 -p 5001:9001 -v /data:/data rustfs/rustfs` with the latest image I could finally access the console webpage. However the default username and password still don't work.

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/8218ceb3-b3f1-42d7-81fc-50f3a7f79208" />

docker log:
```
2025-07-04T02:35:49.275715147Z Flexi logger initialized with file logging to deploy/logs/rustfs.log.log
2025-07-04T02:35:49.275784088Z Log rotation configured for: every day or when size exceeds 100MB, keeping 30 files
2025-07-04T02:35:49.276595848Z 2025-07-04 02:35:49.276144 [38;5;196mERROR[0m [[35mtracing::span[0m] [[34mcrates/obs/src/logger.rs[0m:[34m81[0m] [[32mtokio-runtime-worker[0m:[32mThreadId(4)[0m] log_entry;
2025-07-04T02:35:49.276625579Z 
2025-07-04T02:35:49.276632137Z 2025-07-04 02:35:49.276446 [38;5;208mWARN[0m [[35mrustfs[0m] [[34mrustfs/src/main.rs[0m:[34m178[0m] [[32mmain[0m:[32mThreadId(1)[0m] Detected default credentials 'rustfsadmin:rustfsadmin', we recommend that you change these values with 'RUSTFS_ACCESS_KEY' and 'RUSTFS_SECRET_KEY' environment variables
2025-07-04T02:35:49.276639817Z 
2025-07-04T02:35:49.323979080Z 2025-07-04 02:35:49.323388 [38;5;208mWARN[0m [[35mrustfs_ecstore::cmd::bucket_replication[0m] [[34mcrates/ecstore/src/cmd/bucket_replication.rs[0m:[34m974[0m] [[32mmain[0m:[32mThreadId(1)[0m] init bucket replication pool
2025-07-04T02:35:49.324016681Z 
2025-07-04T02:35:49.324023607Z 2025-07-04 02:35:49.323460 [38;5;208mWARN[0m [[35mrustfs_ecstore::cmd::bucket_replication[0m] [[34mcrates/ecstore/src/cmd/bucket_replication.rs[0m:[34m630[0m] [[32mmain[0m:[32mThreadId(1)[0m] init_bucket_replication_pool 0 0 auto 50
2025-07-04T02:35:49.324030618Z 
2025-07-04T02:35:49.324035710Z 2025-07-04 02:35:49.323500 [38;5;208mWARN[0m [[35mrustfs_ecstore::cmd::bucket_replication[0m] [[34mcrates/ecstore/src/cmd/bucket_replication.rs[0m:[34m697[0m] [[32mmain[0m:[32mThreadId(1)[0m] work size is: 10
2025-07-04T02:35:49.324041721Z 
2025-07-04T02:35:49.324046408Z 2 resize_lrg_workers
2025-07-04T02:35:49.372611836Z 2025-07-04 02:35:49.372396 [38;5;208mWARN[0m [[35mrustfs::update_checker[0m] [[34mrustfs/src/update_checker.rs[0m:[34m181[0m] [[32mtokio-runtime-worker[0m:[32mThreadId(5)[0m] Semantic version comparison failed, using string comparison
2025-07-04T02:35:49.372640158Z 
2025-07-04T03:05:50.606434153Z 2025-07-04 03:05:50.015169 [38;5;196mERROR[0m [[35mrustfs_ecstore::disk::local[0m] [[34mcrates/ecstore/src/disk/local.rs[0m:[34m281[0m] [[32mtokio-runtime-worker[0m:[32mThreadId(61)[0m] cleanup_deleted_objects error: Io(Os { code: 116, kind: StaleNetworkFileHandle, message: "Stale file handle" })
2025-07-04T03:05:50.686162198Z 
```

Besides, I found that the console webpage keeps consuming huge CPU resources (I use Chrome)

**Comment by iYting** [comment]
> Yes, we are working on fixing this.
> 
> You can try using this image first. `podman run -d -p 9000:9000 -p 9001:9001 -v /data:/data quay.io/rustfs/rustfs ` Don't put this docker into production yet.

@loverustfs 
**The issue still persists**
`podman run -d -p 9000:9000 -p 9001:9001 -v /d/docker/rustfs/data:/data quay.io/rustfs/rustfs`

**log:**
```
2025-07-04 04:36:18.654862 WARN [rustfs_ecstore::disk::os] [crates/ecstore/src/disk/os.rs:155] [tokio-runtime-worker:ThreadId(8)] reliable_rename failed. src_file_path: "/data/.rustfs.sys/tmp/c75c0213-0588-4acb-ab2a-a76a291be99f/3e63c901-d190-47ed-bf10-7b7522458931/", dst_file_path: "/data/.rustfs.sys/pool.bin/3e63c901-d190-47ed-bf10-7b7522458931/", base_dir: "/data/.rustfs.sys", err: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

2025-07-04 04:36:18.657986 ERROR [rustfs_ecstore::config::com] [crates/ecstore/src/config/com.rs:114] [main:ThreadId(1)] save_config_with_opts: err: FileAccessDenied, file: pool.bin

2025-07-04 04:36:18.658082 ERROR [rustfs_ecstore::store] [crates/ecstore/src/store.rs:258] [main:ThreadId(1)] init err: File access denied

2025-07-04 04:36:18.658090 ERROR [rustfs_ecstore::store] [crates/ecstore/src/store.rs:259] [main:ThreadId(1)] retry after  5 second

2025-07-04 04:36:23.659471 ERROR [rustfs] [rustfs/src/main.rs:561] [main:ThreadId(1)] ECStore::new Io(Custom { kind: Other, error: "ec init failed" })
Error: Custom { kind: Other, error: "ec init failed" }
```

**Comment by loverustfs** [comment]
> By using `docker run -d -p 5000:9000 -p 5001:9001 -v /data:/data rustfs/rustfs` with the latest image I could finally access the console webpage. However the default username and password still don't work.

We found this anomaly. We use special effects in our front-end webpage. If WebGL is not enabled, it will appear very slow.

To solve the problem of being unable to log in successfully:

1. Could I see the port information and IP information of the network link in your Chrome Console?

2. Could I see your docker image ID?

**Comment by loverustfs** [comment]
> /d/docker/rustfs/data

1. Did you download the latest docker image? What is the docker image id?

2. How are the permissions of the /d/docker/rustfs/data folder configured?

**Comment by loverustfs** [comment]
> By using `docker run -d -p 5000:9000 -p 5001:9001 -v /data:/data rustfs/rustfs` with the latest image I could finally access the console webpage. However the default username and password still don't work.
> 
> <img alt="Image" width="1064" src="https://private-user-images.githubusercontent.com/9637282/462283628-8218ceb3-b3f1-42d7-81fc-50f3a7f79208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE2MjY2MTQsIm5iZiI6MTc1MTYyNjMxNCwicGF0aCI6Ii85NjM3MjgyLzQ2MjI4MzYyOC04MjE4Y2ViMy1iM2YxLTQyZDctODFmYy01MGYzYTdmNzkyMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MDRUMTA1MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ1NzkwNzczN2EyYmIxNTE0NDJiYzM1MDdlMmFjNjU4Nzk2YWQxYzg2MGI1MDAzZWZmNTE1YzVhNjJkMzlkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HptYnG2GSW39hVmd6H0EHYoZcKNhXc-ShWwx3aMwDIg">
> docker log:
> 
> ```
> 2025-07-04T02:35:49.275715147Z Flexi logger initialized with file logging to deploy/logs/rustfs.log.log
> 2025-07-04T02:35:49.275784088Z Log rotation configured for: every day or when size exceeds 100MB, keeping 30 files
> 2025-07-04T02:35:49.276595848Z 2025-07-04 02:35:49.276144 �[38;5;196mERROR�[0m [�[35mtracing::span�[0m] [�[34mcrates/obs/src/logger.rs�[0m:�[34m81�[0m] [�[32mtokio-runtime-worker�[0m:�[32mThreadId(4)�[0m] log_entry;
> 2025-07-04T02:35:49.276625579Z 
> 2025-07-04T02:35:49.276632137Z 2025-07-04 02:35:49.276446 �[38;5;208mWARN�[0m [�[35mrustfs�[0m] [�[34mrustfs/src/main.rs�[0m:�[34m178�[0m] [�[32mmain�[0m:�[32mThreadId(1)�[0m] Detected default credentials 'rustfsadmin:rustfsadmin', we recommend that you change these values with 'RUSTFS_ACCESS_KEY' and 'RUSTFS_SECRET_KEY' environment variables
> 2025-07-04T02:35:49.276639817Z 
> 2025-07-04T02:35:49.323979080Z 2025-07-04 02:35:49.323388 �[38;5;208mWARN�[0m [�[35mrustfs_ecstore::cmd::bucket_replication�[0m] [�[34mcrates/ecstore/src/cmd/bucket_replication.rs�[0m:�[34m974�[0m] [�[32mmain�[0m:�[32mThreadId(1)�[0m] init bucket replication pool
> 2025-07-04T02:35:49.324016681Z 
> 2025-07-04T02:35:49.324023607Z 2025-07-04 02:35:49.323460 �[38;5;208mWARN�[0m [�[35mrustfs_ecstore::cmd::bucket_replication�[0m] [�[34mcrates/ecstore/src/cmd/bucket_replication.rs�[0m:�[34m630�[0m] [�[32mmain�[0m:�[32mThreadId(1)�[0m] init_bucket_replication_pool 0 0 auto 50
> 2025-07-04T02:35:49.324030618Z 
> 2025-07-04T02:35:49.324035710Z 2025-07-04 02:35:49.323500 �[38;5;208mWARN�[0m [�[35mrustfs_ecstore::cmd::bucket_replication�[0m] [�[34mcrates/ecstore/src/cmd/bucket_replication.rs�[0m:�[34m697�[0m] [�[32mmain�[0m:�[32mThreadId(1)�[0m] work size is: 10
> 2025-07-04T02:35:49.324041721Z 
> 2025-07-04T02:35:49.324046408Z 2 resize_lrg_workers
> 2025-07-04T02:35:49.372611836Z 2025-07-04 02:35:49.372396 �[38;5;208mWARN�[0m [�[35mrustfs::update_checker�[0m] [�[34mrustfs/src/update_checker.rs�[0m:�[34m181�[0m] [�[32mtokio-runtime-worker�[0m:�[32mThreadId(5)�[0m] Semantic version comparison failed, using string comparison
> 2025-07-04T02:35:49.372640158Z 
> 2025-07-04T03:05:50.606434153Z 2025-07-04 03:05:50.015169 �[38;5;196mERROR�[0m [�[35mrustfs_ecstore::disk::local�[0m] [�[34mcrates/ecstore/src/disk/local.rs�[0m:�[34m281�[0m] [�[32mtokio-runtime-worker�[0m:�[32mThreadId(61)�[0m] cleanup_deleted_objects error: Io(Os { code: 116, kind: StaleNetworkFileHandle, message: "Stale file handle" })
> 2025-07-04T03:05:50.686162198Z 
> ```
> 
> Besides, I found that the console webpage keeps consuming huge CPU resources (I use Chrome)

## Steps

@iYting @biociao 

I created two clean virtual servers on the cloud.

1. yum install docker -y
<img width="1025" alt="Image" src="https://github.com/user-attachments/assets/19c6323e-cfd4-42cb-a97e-74406c882e85" />

2. systemctl enable docker && systemctl start docker  &&  systemctl status docker

<img width="1122" alt="Image" src="https://github.com/user-attachments/assets/0fa81002-26cc-4672-b289-e87d3c3f68d3" />


3. mkdir /data/

<img width="667" alt="Image" src="https://github.com/user-attachments/assets/b7bc10ce-1247-477e-adb0-8758c11eb069" />

4.   docker run -d -p 5000:9000 -p 5001:9001 -v /data:/data rustfs/rustfs  &&  docker ps -a

<img width="1270" alt="Image" src="https://github.com/user-attachments/assets/07e0565c-1092-46bf-bceb-23432e2e7a86" />


5. Add firewall rules.

<img width="998" alt="Image" src="https://github.com/user-attachments/assets/e9ccbe3e-df2d-4dbc-8d84-10a0dc40385a" />


6. Access failed 

<img width="1332" alt="Image" src="https://github.com/user-attachments/assets/e8101dbe-3f05-46d9-9602-79f00d5b88f8" />


## Summary

The Dockerfile has an error in the ports configuration file.

<img width="632" alt="Image" src="https://github.com/user-attachments/assets/94eb31ea-92ce-45b5-98a8-bcb85dd96b8a" />

**Comment by loverustfs** [comment]
@biociao 

I'm very sorry! It caused you trouble.

Solution:

1. You temporarily change to ports 9000 and 9001;

2. Wait for us to modify the Dockerfile correctly;

3. Or you can help us submit a PR,Hahahaha

**Comment by loverustfs** [comment]
> podman run -d -p 9000:9000 -p 9001:9001 -v /d/docker/rustfs/data:/data quay.io/rustfs/rustfs


Hi, @iYting  I'm sorry for causing you trouble.

I prepared a clean virtual machine.

1. Install podman
2. Create a directory
3. Start podman

Start and log in successfully.

I guess it may be because of your directory permissions.

<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/5a4c078e-837a-429a-bb66-5d5a7cb53b4e" />


```
yum install podman -y
mkdir -p /d/docker/rustfs/data
podman run -d -p 9000:9000 -p 9001:9001 -v /d/docker/rustfs/data:/data quay.io/rustfs/rustfs
```

<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/5c31933a-d67a-407b-a5e9-b7eb6ec18940" />







<img width="1080" alt="Image" src="https://github.com/user-attachments/assets/896c3846-de96-43c2-85e8-249c6a058180" />

**Comment by loverustfs** [comment]
@biociao @iYting @WangNingkai 

https://github.com/rustfs/rustfs/pull/90

This bug is fixed.

If you confirm that it has been resolved, we will close this issue.

**Comment by biociao** [comment]
With the latest image:
```bash
docker run -d -p 5700:9000 -p 5701:9001 -v /d/docker/rustfs/data:/data quay.io/rustfs/rustfs
```
Still, cannot login with `rustfsadmin`

<img width="1552" height="930" alt="Image" src="https://github.com/user-attachments/assets/c826c705-220d-4def-b21d-c33f764e4fc0" />

For security reason, I cannot test on port 9000 and 9001.

**Comment by loverustfs** [comment]
> With the latest image:
> 
> docker run -d -p 5700:9000 -p 5701:9001 -v /d/docker/rustfs/data:/data quay.io/rustfs/rustfs
> Still, cannot login with `rustfsadmin`
> 
> <img alt="Image" width="1552" height="930" src="https://private-user-images.githubusercontent.com/9637282/463613542-c826c705-220d-4def-b21d-c33f764e4fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE5NzcyNTEsIm5iZiI6MTc1MTk3Njk1MSwicGF0aCI6Ii85NjM3MjgyLzQ2MzYxMzU0Mi1jODI2YzcwNS0yMjBkLTRkZWYtYjIxZC1jMzNmNzY0ZTRmYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MDhUMTIxNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc1NDQzMmE3NmQ3MjY0YzAxOGZjYzRhNWEzY2EwYTQ2ZGYxMjRiODllNTc1M2QwNjMzYWRhYWRlM2UzZGY3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zccYeK1AEWbDZmH7GN65ZhaDaIcZnc4_ZCmnQfNd29Y">
> For security reason, I cannot test on port 9000 and 9001.

Thank you. @biociao 

OK, our build did not generate successfully. The binary package in docker is still old.

We are working on fixing it.

**Comment by houseme** [comment]
docker docs：https://docs.rustfs.com/zh/installation/docker.html

**Comment by loverustfs** [comment]
Hi @biociao @iYting @WangNingkai ,

Please check the latest Docker Image, this bug has been fixed.

**Comment by iYting** [comment]
> Hi [@biociao](https://github.com/biociao) [@iYting](https://github.com/iYting) [@WangNingkai](https://github.com/WangNingkai) ,
> 
> Please check the latest Docker Image, this bug has been fixed.

It works

**Comment by cruvie** [comment]
@loverustfs no linux/arm64 for latest docker image?

**Comment by xx1906** [comment]
> In addition, I would like to ask where is the demo account?

这个问题怎么解决的？

**Comment by xx1906** [comment]
> docker docs：https://docs.rustfs.com/zh/installation/docker.html

我就是用了 官网的 docker-compose 文件，数据挂载到本地就报权限不足。。。。

**Comment by loverustfs** [comment]
> > docker docs：https://docs.rustfs.com/zh/installation/docker.html
> 
> 我就是用了 官网的 docker-compose 文件，数据挂载到本地就报权限不足。。。。

#893

**Comment by xx1906** [comment]
> [@biociao](https://github.com/biociao)
> 
> I'm very sorry! It caused you trouble.
> 
> Solution:
> 
> 1. You temporarily change to ports 9000 and 9001;
> 2. Wait for us to modify the Dockerfile correctly;
> 3. Or you can help us submit a PR,Hahahaha

大哥，别笑我是认真的，真没解决

<img width="1860" height="1105" alt="Image" src="https://github.com/user-attachments/assets/2a336bb8-90ce-4504-b47e-1cc181786c07" />

**Comment by xx1906** [comment]
> > [@biociao](https://github.com/biociao)
> > I'm very sorry! It caused you trouble.
> > Solution:
> > 
> > 1. You temporarily change to ports 9000 and 9001;
> > 2. Wait for us to modify the Dockerfile correctly;
> > 3. Or you can help us submit a PR,Hahahaha
> 
> 大哥，别笑我是认真的，真没解决
> 
> <img alt="Image" width="1860" height="1105" src="https://private-user-images.githubusercontent.com/67250607/517799118-2a336bb8-90ce-4504-b47e-1cc181786c07.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM4Nzk1MjYsIm5iZiI6MTc2Mzg3OTIyNiwicGF0aCI6Ii82NzI1MDYwNy81MTc3OTkxMTgtMmEzMzZiYjgtOTBjZS00NTA0LWI0N2UtMWNjMTgxNzg2YzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIzVDA2MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNGFlY2E1NTU4ZDE3MzgwYTdkNDljNDE1OTllNzA1NjIzMDY1YjQ3Nzg4ZGE0ODI5MDUxZDA5NDBhZmJlZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4zC7fDkPOcuBBQ-L8FhUMSZAZQkb5HVtIpPWe1ornxY">

补充一下，挂载宿主机的文件夹， windows 10 可以正常， debian 12.2.0 上就有问题

**Comment by xx1906** [comment]
> > > [@biociao](https://github.com/biociao)
> > > I'm very sorry! It caused you trouble.
> > > Solution:
> > > 
> > > 1. You temporarily change to ports 9000 and 9001;
> > > 2. Wait for us to modify the Dockerfile correctly;
> > > 3. Or you can help us submit a PR,Hahahaha
> > 
> > 
> > 大哥，别笑我是认真的，真没解决
> > <img alt="Image" width="1860" height="1105" src="https://private-user-images.githubusercontent.com/67250607/517799118-2a336bb8-90ce-4504-b47e-1cc181786c07.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM4Nzk1MjYsIm5iZiI6MTc2Mzg3OTIyNiwicGF0aCI6Ii82NzI1MDYwNy81MTc3OTkxMTgtMmEzMzZiYjgtOTBjZS00NTA0LWI0N2UtMWNjMTgxNzg2YzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIzVDA2MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNGFlY2E1NTU4ZDE3MzgwYTdkNDljNDE1OTllNzA1NjIzMDY1YjQ3Nzg4ZGE0ODI5MDUxZDA5NDBhZmJlZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4zC7fDkPOcuBBQ-L8FhUMSZAZQkb5HVtIpPWe1ornxY">
> 
> 补充一下，挂载宿主机的文件夹， windows 10 可以正常， debian 12.2.0 上就有问题

还是你们构建 dockerfile 这个地方的问题， 
RUN addgroup -g 10001 -S rustfs && \
    adduser -u 10001 -G rustfs -S rustfs -D && \
    mkdir -p /data /logs && \
    chown -R rustfs:rustfs /data /logs && \
    chmod 0750 /data /logs
 然后我在宿主机上改 
py38) xx in /storage/prod/xx/deployment/rustfs λ sudo chown -R 10001:10001 data
[sudo] password for xx:
(py38) xx in /storage/prod/xx/deployment/rustfs λ sudo chown -R 10001:10001 logs
(py38) xx in /storage/prod/xx/deployment/rustfs λ sudo chown -R 10001:10001 logs
才能够正常使用

**Comment by 10fish** [comment]
Just in case anyone else runs into the same permission issue when using *Podman*, try running the chown command inside `podman unshare`:

```bash
podman unshare chown -R 10001:10001 data logs
```
This did the trick on my end.
