### ISSUE TITLE
Unable to change bucket's access policy to custom

### ISSUE THREAD

**Issue by 3himmers** [rustfs/rustfs#411]
After creating the bucket, I cannot change the bucket's access policy to custom.

version:1.0.0-alpha.42

**Comment by loverustfs** [comment]
Confirm this bug.



<img width="2388" height="1522" alt="Image" src="https://github.com/user-attachments/assets/eddecbd2-3bcc-4688-9067-28358aa00e8e" />

**Comment by hidevo** [comment]
Changing `"Principal` to `{"AWS": ["*"]}` can save successfully. The complete JSON is as follows:


```json
{
  "ID": "",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:GetObject"
      ],
      "NotAction": [],
      "Resource": [
        "arn:aws:s3:::demo/*"
      ],
      "NotResource": [],
      "Condition": {}
    }
  ]
}
```
However, this configuration will not take effect, and the page configuration is not updated to the custom value, and it still uses the previous value (public or private)


<img width="482" height="185" alt="Image" src="https://github.com/user-attachments/assets/e2947bc8-1e55-4f69-993f-41ecbb195862" />

**Comment by loverustfs** [comment]
Hi @3himmers ,

This bug did not occur in rustfs 1.0.0-alpha.45.
Is this bug still present?


```
 rustfs --version
rustfs 1.0.0-alpha.45
build time   : 2025-08-19 15:02:49 +00:00
build profile: release
build os     : linux-x86_64
rust version : rustc 1.89.0 (29483883e 2025-08-04)
rust channel : stable-x86_64-unknown-linux-gnu
git branch   :
git commit   : e9c9a2d1f26ec9d266db12b90f2d57354839ae3c
git tag      : 1.0.0-alpha.45
git status   :
```

<img width="2482" height="1440" alt="Image" src="https://github.com/user-attachments/assets/2e21e6db-55b0-4470-99dc-326d85bc4f79" />

**Comment by loverustfs** [comment]
Please help confirm whether this bug still exists after the upgrade.
Thank you.

@wsaio

**Comment by 3himmers** [comment]
Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.

> Hi [@3himmers](https://github.com/3himmers) ,
> 
> This bug did not occur in rustfs 1.0.0-alpha.45. Is this bug still present?
> 
> ```
>  rustfs --version
> rustfs 1.0.0-alpha.45
> build time   : 2025-08-19 15:02:49 +00:00
> build profile: release
> build os     : linux-x86_64
> rust version : rustc 1.89.0 (29483883e 2025-08-04)
> rust channel : stable-x86_64-unknown-linux-gnu
> git branch   :
> git commit   : e9c9a2d1f26ec9d266db12b90f2d57354839ae3c
> git tag      : 1.0.0-alpha.45
> git status   :
> ```
> 
> <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155562731/480610626-2e21e6db-55b0-4470-99dc-326d85bc4f79.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU4NDU3NDcsIm5iZiI6MTc1NTg0NTQ0NywicGF0aCI6Ii8xNTU1NjI3MzEvNDgwNjEwNjI2LTJlMjFlNmRiLTU1YjAtNDQ3MC05OWRjLTMyNmQ4NWJjNGY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyMlQwNjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjg2YzA1YTVjZTM3MzBiOWZiYjM1YTk1MmFmNjA4ZDhmYzlkNWM1MDcxMDI1ZTEwNGZmMzVlY2JjMDU3YjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._B6nHpq7Uevqwf5SCZwnO6NfLDko46JYC-W2sh54LhM">

Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.

**Comment by loverustfs** [comment]
> Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.
> 
> > Hi [@3himmers](https://github.com/3himmers) ,
> > This bug did not occur in rustfs 1.0.0-alpha.45. Is this bug still present?
> > ```
> >  rustfs --version
> > rustfs 1.0.0-alpha.45
> > build time   : 2025-08-19 15:02:49 +00:00
> > build profile: release
> > build os     : linux-x86_64
> > rust version : rustc 1.89.0 (29483883e 2025-08-04)
> > rust channel : stable-x86_64-unknown-linux-gnu
> > git branch   :
> > git commit   : e9c9a2d1f26ec9d266db12b90f2d57354839ae3c
> > git tag      : 1.0.0-alpha.45
> > git status   :
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155562731/480610626-2e21e6db-55b0-4470-99dc-326d85bc4f79.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU4NDU3NDcsIm5iZiI6MTc1NTg0NTQ0NywicGF0aCI6Ii8xNTU1NjI3MzEvNDgwNjEwNjI2LTJlMjFlNmRiLTU1YjAtNDQ3MC05OWRjLTMyNmQ4NWJjNGY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyMlQwNjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjg2YzA1YTVjZTM3MzBiOWZiYjM1YTk1MmFmNjA4ZDhmYzlkNWM1MDcxMDI1ZTEwNGZmMzVlY2JjMDU3YjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._B6nHpq7Uevqwf5SCZwnO6NfLDko46JYC-W2sh54LhM">
> 
> Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.

OK.
1. Download the latest installation package and unzip it.
2. mv /usr/local/bin/rustfs /usr/local/bin/rustfs.bak
3. Move NEW-PACKAGE to /usr/local/bin/rustfs
4. systemctl restart rustfs

**Comment by 3himmers** [comment]
> > Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.
> > > Hi [@3himmers](https://github.com/3himmers) ,
> > > This bug did not occur in rustfs 1.0.0-alpha.45. Is this bug still present?
> > > ```
> > >  rustfs --version
> > > rustfs 1.0.0-alpha.45
> > > build time   : 2025-08-19 15:02:49 +00:00
> > > build profile: release
> > > build os     : linux-x86_64
> > > rust version : rustc 1.89.0 (29483883e 2025-08-04)
> > > rust channel : stable-x86_64-unknown-linux-gnu
> > > git branch   :
> > > git commit   : e9c9a2d1f26ec9d266db12b90f2d57354839ae3c
> > > git tag      : 1.0.0-alpha.45
> > > git status   :
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155562731/480610626-2e21e6db-55b0-4470-99dc-326d85bc4f79.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU4NDU3NDcsIm5iZiI6MTc1NTg0NTQ0NywicGF0aCI6Ii8xNTU1NjI3MzEvNDgwNjEwNjI2LTJlMjFlNmRiLTU1YjAtNDQ3MC05OWRjLTMyNmQ4NWJjNGY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyMlQwNjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjg2YzA1YTVjZTM3MzBiOWZiYjM1YTk1MmFmNjA4ZDhmYzlkNWM1MDcxMDI1ZTEwNGZmMzVlY2JjMDU3YjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._B6nHpq7Uevqwf5SCZwnO6NfLDko46JYC-W2sh54LhM">
> > 
> > 
> > Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.
> 
> OK.
> 
> 1. Download the latest installation package and unzip it.
> 2. mv /usr/local/bin/rustfs /usr/local/bin/rustfs.bak
> 3. Move NEW-PACKAGE to /usr/local/bin/rustfs
> 4. systemctl restart rustfs

I upgraded to version 46, and now I can save custom policies, but after refreshing, it still shows public.

**Comment by loverustfs** [comment]
> > > Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.
> > > > Hi [@3himmers](https://github.com/3himmers) ,
> > > > This bug did not occur in rustfs 1.0.0-alpha.45. Is this bug still present?
> > > > ```
> > > >  rustfs --version
> > > > rustfs 1.0.0-alpha.45
> > > > build time   : 2025-08-19 15:02:49 +00:00
> > > > build profile: release
> > > > build os     : linux-x86_64
> > > > rust version : rustc 1.89.0 (29483883e 2025-08-04)
> > > > rust channel : stable-x86_64-unknown-linux-gnu
> > > > git branch   :
> > > > git commit   : e9c9a2d1f26ec9d266db12b90f2d57354839ae3c
> > > > git tag      : 1.0.0-alpha.45
> > > > git status   :
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155562731/480610626-2e21e6db-55b0-4470-99dc-326d85bc4f79.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU4NDU3NDcsIm5iZiI6MTc1NTg0NTQ0NywicGF0aCI6Ii8xNTU1NjI3MzEvNDgwNjEwNjI2LTJlMjFlNmRiLTU1YjAtNDQ3MC05OWRjLTMyNmQ4NWJjNGY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyMlQwNjUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjg2YzA1YTVjZTM3MzBiOWZiYjM1YTk1MmFmNjA4ZDhmYzlkNWM1MDcxMDI1ZTEwNGZmMzVlY2JjMDU3YjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._B6nHpq7Uevqwf5SCZwnO6NfLDko46JYC-W2sh54LhM">
> > > 
> > > 
> > > Sorry, I couldn't find the update steps in the documentation. Could you provide an update operation document? I deployed it directly on Linux.
> > 
> > OK.
> > 
> > 1. Download the latest installation package and unzip it.
> > 2. mv /usr/local/bin/rustfs /usr/local/bin/rustfs.bak
> > 3. Move NEW-PACKAGE to /usr/local/bin/rustfs
> > 4. systemctl restart rustfs
> 
> I upgraded to version 46, and now I can save custom policies, but after refreshing, it still shows public.

Ok, we'll fix this bug and get back to you.

**Comment by loverustfs** [comment]
This bug has been fixed, please confirm.


<img width="2578" height="1280" alt="Image" src="https://github.com/user-attachments/assets/ca140a75-3157-43d1-bed9-c05da04ad86d" />

**Comment by loverustfs** [comment]
@3himmers ,

If you have any other bugs, please feel free to contact us.

**Comment by 3himmers** [comment]
> This bug has been fixed, please confirm.
> 
> <img alt="Image" width="2000" height="1280" src="https://private-user-images.githubusercontent.com/155562731/483574140-ca140a75-3157-43d1-bed9-c05da04ad86d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1MzU3NjcsIm5iZiI6MTc1NjUzNTQ2NywicGF0aCI6Ii8xNTU1NjI3MzEvNDgzNTc0MTQwLWNhMTQwYTc1LTMxNTctNDNkMS1iZWQ5LWMwNWRhMDRhZDg2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQwNjMxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmU4MTA1MmNmYTEzNDVlOTZmZGQ3ZDFjOThkYzgyMmZmNWViYWIzMWVkY2M3NDZiMjE3NTU2ODNjNTQzZWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.azzjgGLYcBB8tdbEwZWZ8eZOB60nhGmoOF21GpZ-p5s">

Unfortunately, this bug appears to still be present. I've updated to the latest version, but the issue persists. I initially thought it might be a problem with my server, but the issue remains even on the official demo site.

**Comment by loverustfs** [comment]
> > This bug has been fixed, please confirm.
> > 
> > <img alt="Image" width="2000" height="1280" src="https://private-user-images.githubusercontent.com/155562731/483574140-ca140a75-3157-43d1-bed9-c05da04ad86d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1MzU3NjcsIm5iZiI6MTc1NjUzNTQ2NywicGF0aCI6Ii8xNTU1NjI3MzEvNDgzNTc0MTQwLWNhMTQwYTc1LTMxNTctNDNkMS1iZWQ5LWMwNWRhMDRhZDg2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQwNjMxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmU4MTA1MmNmYTEzNDVlOTZmZGQ3ZDFjOThkYzgyMmZmNWViYWIzMWVkY2M3NDZiMjE3NTU2ODNjNTQzZWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.azzjgGLYcBB8tdbEwZWZ8eZOB60nhGmoOF21GpZ-p5s">
> 
> Unfortunately, this bug appears to still be present. I've updated to the latest version, but the issue persists. I initially thought it might be a problem with my server, but the issue remains even on the official demo site.

The demo site entered the strategy you said and it still didn't reappear.
The displayed status is still user-defined.

Can you tell me about your operation steps?

**Comment by loverustfs** [comment]
This bug just appeared on the demo site, we will find out the cause.

Thank you.

**Comment by loverustfs** [comment]
@3himmers ,

If the custom policy doesn't display after saving, it's because you've created the same policy as the public policy.

If the custom policy is public, it will remain public even after saving.

Only when the changes differ from public or private will the policy become custom.

**Comment by loverustfs** [comment]
We believe this is a bug-free solution. Please confirm your policy.

**Comment by 3himmers** [comment]
> We believe this is a bug-free solution. Please confirm your policy.

I've confirmed it's exactly as you said. My apologies for my earlier mistake. Thank you for the quick fix.

**Comment by loverustfs** [comment]
> > We believe this is a bug-free solution. Please confirm your policy.
> 
> I've confirmed it's exactly as you said. My apologies for my earlier mistake. Thank you for the quick fix.

Don't worry, please feel free to contact us if you find any bugs.

I wish you all the best, and I'll close this issue.
