### ISSUE TITLE
Unable to login since i updated from alpha.52

### ISSUE THREAD

**Issue by RealFascinated** [rustfs/rustfs#564]
**Describe the bug**
Since i updated from alpha.52 the console was separated and i got that all setup and working but i can no longer login to the website. It worked previously. Am i doing something wrong?

**To Reproduce**
Use a version past alpha.52
Then login

**Expected behavior**
To be able to login

**Screenshots**

<img width="2786" height="1572" alt="Image" src="https://github.com/user-attachments/assets/ef6d8b69-deaa-4fa8-bfac-0de137d6b58e" />

**Comment by RealFascinated** [comment]
The S3 functionality works fine, just the web panel is having issues

**Comment by loverustfs** [comment]
@RealFascinated ,

Thank you for your feedback.

We will test this upgrade and login again

**Comment by loverustfs** [comment]
We are trying to do a re-test, is there any more configuration information?

**Comment by loverustfs** [comment]
Hi @RealFascinated ,

We upgraded from alpha.52 to the latest version, and everything is working correctly.

Looking at the screenshot, we found that:

You are using Cloudflare as a proxy.

Could you please try accessing it directly without the proxy and see if the error still occurs?

**Comment by RealFascinated** [comment]
> Hi @RealFascinated ,
> 
> We upgraded from alpha.52 to the latest version, and everything is working correctly.
> 
> Looking at the screenshot, we found that:
> 
> You are using Cloudflare as a proxy.
> 
> Could you please try accessing it directly without the proxy and see if the error still occurs?

Yes the error still happens if I go directly to the ip and port

**Comment by loverustfs** [comment]
> > Hi [@RealFascinated](https://github.com/RealFascinated) ,
> > We upgraded from alpha.52 to the latest version, and everything is working correctly.
> > Looking at the screenshot, we found that:
> > You are using Cloudflare as a proxy.
> > Could you please try accessing it directly without the proxy and see if the error still occurs?
> 
> Yes the error still happens if I go directly to the ip and port



OK, thank you for your continued feedback.
Could you please share your steps and configuration files?

I can provide a server to simulate your operation.

We want to reproduce this error.

**Comment by RealFascinated** [comment]
```docker run
  -d
  --name='rufstfs'
  --pids-limit 2048
  -e TZ="Europe/London"
  -e 'RUSTFS_VOLUMES'='/data'
  -e 'RUSTFS_CONSOLE_ENABLE'='true'
  -e 'RUSTFS_ADDRESS'='0.0.0.0:7000'
  -e 'RUSTFS_ACCESS_KEY'=''
  -e 'RUSTFS_SECRET_KEY'=''
  -e 'RUSTFS_ENABLE_SCANNER'='false'
  -e 'RUSTFS_CONSOLE_ADDRESS'='0.0.0.0:7001'
  -e 'RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS'='*'
  -e 'RUSTFS_CORS_ALLOWED_ORIGINS'='*'
  -e 'RUSTFS_EXTERNAL_ADDRESS'=':7000'
  -p '7000:7000/tcp'
  -p '7001:7001/tcp'
  -v '/mnt/disk3/rustfs/data':'/data':'rw'
  -v '/mnt/user/appdata/rustfs/logs':'/logs':'rw' 'rustfs/rustfs:alpha'
```

This is my docker startup command, I do not use any kind of configuration files.

**Comment by volfco** [comment]
I'm encountering the same issue. If the console is running on a separate port and you access the console on that port, the server returns 405 Method not Supported when logging in. 

It works fine on the RUSTFS_ADDRESS but not RUSTFS_CONSOLE_ADDRESS

**Comment by loverustfs** [comment]
> ```
>   -d
>   --name='rufstfs'
>   --pids-limit 2048
>   -e TZ="Europe/London"
>   -e 'RUSTFS_VOLUMES'='/data'
>   -e 'RUSTFS_CONSOLE_ENABLE'='true'
>   -e 'RUSTFS_ADDRESS'='0.0.0.0:7000'
>   -e 'RUSTFS_ACCESS_KEY'=''
>   -e 'RUSTFS_SECRET_KEY'=''
>   -e 'RUSTFS_ENABLE_SCANNER'='false'
>   -e 'RUSTFS_CONSOLE_ADDRESS'='0.0.0.0:7001'
>   -e 'RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS'='*'
>   -e 'RUSTFS_CORS_ALLOWED_ORIGINS'='*'
>   -e 'RUSTFS_EXTERNAL_ADDRESS'=':7000'
>   -p '7000:7000/tcp'
>   -p '7001:7001/tcp'
>   -v '/mnt/disk3/rustfs/data':'/data':'rw'
>   -v '/mnt/user/appdata/rustfs/logs':'/logs':'rw' 'rustfs/rustfs:alpha'
> ```
> 
> This is my docker startup command, I do not use any kind of configuration files.

Thank you very much! We will follow up and test this error again.

**Comment by loverustfs** [comment]
> I'm encountering the same issue. If the console is running on a separate port and you access the console on that port, the server returns 405 Method not Supported when logging in.
> 
> It works fine on the RUSTFS_ADDRESS but not RUSTFS_CONSOLE_ADDRESS

Ok, thanks . 
We will follow up and test this error again.

**Comment by houseme** [comment]
> ```
>   -d
>   --name='rufstfs'
>   --pids-limit 2048
>   -e TZ="Europe/London"
>   -e 'RUSTFS_VOLUMES'='/data'
>   -e 'RUSTFS_CONSOLE_ENABLE'='true'
>   -e 'RUSTFS_ADDRESS'='0.0.0.0:7000'
>   -e 'RUSTFS_ACCESS_KEY'=''
>   -e 'RUSTFS_SECRET_KEY'=''
>   -e 'RUSTFS_ENABLE_SCANNER'='false'
>   -e 'RUSTFS_CONSOLE_ADDRESS'='0.0.0.0:7001'
>   -e 'RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS'='*'
>   -e 'RUSTFS_CORS_ALLOWED_ORIGINS'='*'
>   -e 'RUSTFS_EXTERNAL_ADDRESS'=':7000'
>   -p '7000:7000/tcp'
>   -p '7001:7001/tcp'
>   -v '/mnt/disk3/rustfs/data':'/data':'rw'
>   -v '/mnt/user/appdata/rustfs/logs':'/logs':'rw' 'rustfs/rustfs:alpha'
> ```
> 
> This is my docker startup command, I do not use any kind of configuration files.

use alpha.59 ？The new version of the frontend has not been released yet, so it can only be accessed using `:7000`. You will need to wait for us to release a new version to use `:7001`. Thank you.

**Comment by loverustfs** [comment]
Hi @RealFascinated @volfco ,

I am very sorry for the trouble this has caused you. Many users hoped that we would separate the console and the endpoint, and this was indeed a bug that occurred when we separated the console and endpoint ports.

We have recompiled alpha.59. If you update to the latest alpha.59, will this error message still appear?

**Comment by loverustfs** [comment]
If you can confirm that the bug is resolved, we will close this issue. If the bug still exists, we will continue to work on fixing it. We will get all bugs fixed.

Reminder: If you are using Docker, remember to clear the cache and pull the new Docker image.

**Comment by JaynLau** [comment]
Test in docker from alpha.57 to alpha.59, got `InvalidRequest`.

<img width="329" height="120" alt="Image" src="https://github.com/user-attachments/assets/93531598-a603-424b-b591-a87cecb0d54b" />

**Comment by loverustfs** [comment]
> Test in docker from alpha.57 to alpha.59, got `InvalidRequest`.
> 
> <img alt="Image" width="329" height="120" src="https://private-user-images.githubusercontent.com/1670721/492116706-93531598-a603-424b-b591-a87cecb0d54b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg1NDY4OTEsIm5iZiI6MTc1ODU0NjU5MSwicGF0aCI6Ii8xNjcwNzIxLzQ5MjExNjcwNi05MzUzMTU5OC1hNjAzLTQyNGItYjU5MS1hODdjZWNiMGQ1NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjJUMTMwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM2MWY1NzJkMTZhMThjZGRmNTYwMmNkYzBjZDI3MDllNmRmZmEyOTI0YjgyZmM3NWQyNDc2MTcyNzA5NGU1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jH_9tcssjFi4Rufm72yqEqzAt87u4tQSk0UbzEAuLK0">

@houseme Maybe in the next version we upgrade to alpha.60 can solve this bug?

**Comment by houseme** [comment]
> > Test in docker from alpha.57 to alpha.59, got `InvalidRequest`.
> > <img alt="Image" width="329" height="120" src="https://private-user-images.githubusercontent.com/1670721/492116706-93531598-a603-424b-b591-a87cecb0d54b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg1NDY4OTEsIm5iZiI6MTc1ODU0NjU5MSwicGF0aCI6Ii8xNjcwNzIxLzQ5MjExNjcwNi05MzUzMTU5OC1hNjAzLTQyNGItYjU5MS1hODdjZWNiMGQ1NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjJUMTMwOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM2MWY1NzJkMTZhMThjZGRmNTYwMmNkYzBjZDI3MDllNmRmZmEyOTI0YjgyZmM3NWQyNDc2MTcyNzA5NGU1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jH_9tcssjFi4Rufm72yqEqzAt87u4tQSk0UbzEAuLK0">
> 
> [@houseme](https://github.com/houseme) Maybe in the next version we upgrade to alpha.60 can solve this bug?

Yes, it will be repaired

**Comment by loverustfs** [comment]
Hi @RealFascinated @volfco @JaynLau 

This bug has been fixed in alpha.60. Please confirm after upgrading.

https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.60

**Comment by RealFascinated** [comment]
I updated to the latest tag on docker (alpha.60) and i still have the same issue.
<img width="2766" height="1306" alt="Image" src="https://github.com/user-attachments/assets/1541b568-5f13-4e29-8ca4-9378d39fc350" />

There is also this issue. It seems to use the wrong URL to access something

<img width="1354" height="700" alt="Image" src="https://github.com/user-attachments/assets/dd27a746-6c3c-4a65-be34-e75990a2a79b" />

**Comment by houseme** [comment]
1. Please confirm whether you are currently using containerized deployment or binary deployment. Containerized deployment usually involves using tools like Docker, while binary deployment may involve directly running the compiled program.


2. The port forwarded by `rustfs.fascinated.cc` should be the port corresponding to the `RUSTFS_CONSOLE_ADDRESS` you have configured on the container or server, which is typically 9001.


3. Please provide the environment variable (env) configuration information you used to start the container, especially the following environment variables:

   - `RUSTFS_ADDRESS`

   - `RUSTFS_CONSOLE_ADDRESS`

   - `RUSTFS_EXTERNAL_ADDRESS`

   - Other environment variables that may affect the login function.


This information will help us better understand your issue and further diagnose and resolve the problem.

@RealFascinated

**Comment by JaynLau** [comment]
| From | To | Result |
| --- | --- | --- |
| alpha.57  | alpha.58 | N |
| alpha.57  | alpha.59 | N |
| alpha.57  | alpha.60 | N |
| alpha.58  | alpha.59 | Y |
| alpha.58  | alpha.60 | Y |
| alpha.59  | alpha.60 | Y |

**Comment by loverustfs** [comment]
> From	To	Result
> alpha.57	alpha.58	N
> alpha.57	alpha.59	N
> alpha.57	alpha.60	N
> alpha.58	alpha.59	Y
> alpha.58	alpha.60	Y
> alpha.59	alpha.60	Y

Ok, thank you for your feedback. If you have any bug please contract me.

**Comment by RealFascinated** [comment]
> ```
>   -d
>   --name='rufstfs'
>   --pids-limit 2048
>   -e TZ="Europe/London"
>   -e 'RUSTFS_VOLUMES'='/data'
>   -e 'RUSTFS_CONSOLE_ENABLE'='true'
>   -e 'RUSTFS_ADDRESS'='0.0.0.0:7000'
>   -e 'RUSTFS_ACCESS_KEY'=''
>   -e 'RUSTFS_SECRET_KEY'=''
>   -e 'RUSTFS_ENABLE_SCANNER'='false'
>   -e 'RUSTFS_CONSOLE_ADDRESS'='0.0.0.0:7001'
>   -e 'RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS'='*'
>   -e 'RUSTFS_CORS_ALLOWED_ORIGINS'='*'
>   -e 'RUSTFS_EXTERNAL_ADDRESS'=':7000'
>   -p '7000:7000/tcp'
>   -p '7001:7001/tcp'
>   -v '/mnt/disk3/rustfs/data':'/data':'rw'
>   -v '/mnt/user/appdata/rustfs/logs':'/logs':'rw' 'rustfs/rustfs:alpha'
> ```
> 
> This is my docker startup command, I do not use any kind of configuration files.

my current env vars is the same as this, but i use the :latest tag now @houseme. Am i supposed to use `RUSTFS_EXTERNAL_ADDRESS `, if so. how ?

**Comment by houseme** [comment]
Try `alpha.60`,example:
```shell
docker run -d --name rustfs60 -p 9159:9000 -p 9151:9001 -e RUSTFS_EXTERNAL_ADDRESS=":9159" rustfs/rustfs:1.0.0-alpha.60
```

**Comment by RealFascinated** [comment]
The config.json is still going to the wrong port (should be 443/no port) and I still can't login "Method not allowed"

<img width="802" height="784" alt="Image" src="https://github.com/user-attachments/assets/6f4bfe63-b1b6-4073-8fe7-6d70eacd0c1a" />

**Comment by houseme** [comment]
> The config.json is still going to the wrong port (should be 443/no port) and I still can't login "Method not allowed"
> 
> <img alt="Image" width="802" height="784" src="https://private-user-images.githubusercontent.com/67254223/494042786-6f4bfe63-b1b6-4073-8fe7-6d70eacd0c1a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4NTc0NjgsIm5iZiI6MTc1ODg1NzE2OCwicGF0aCI6Ii82NzI1NDIyMy80OTQwNDI3ODYtNmY0YmZlNjMtYjFiNi00MDczLThmZTctNmQ3MGVhY2QwYzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI2VDAzMjYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OTg0OGQ1MTFmZTIwM2NhMmExZmQwZWZmYTM3MGQ0ZjM4ODU1YmE2Yzk4MWM3YWU2ZGE1NzE5MTJkMDRjNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.02V1ZtLzS55h0ugl2d43tFOFjWg1RKQPVUI6ycvqlOY">

The domain name binding points to the port of `:7001`, and the access path will be normal instead of `:7000`. In this version,`API SDK` and `Console` have been separated

**Comment by alexbaeza** [comment]
Hi all, I am using the following env vars:

```
    environment:
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_EXTERNAL_ADDRESS: ":9000"
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_CONSOLE_RATE_LIMIT_ENABLE: "true"
      RUSTFS_CONSOLE_RATE_LIMIT_RPM: "60"
      RUSTFS_CONSOLE_AUTH_TIMEOUT: "1800"

```

But I am unable to login, when I try to login via the UI console on port `:9001` It tries to make a POST request to the root and it returns a 405. 

Can anyone advice?

Running on:
```    
image:
      repository: rustfs/rustfs
      tag: 1.0.0-alpha.61
```

<img width="451" height="238" alt="Image" src="https://github.com/user-attachments/assets/4927d4a6-140a-4dab-8a6d-2efacc541d6c" />

Many thanks

**Comment by houseme** [comment]
> Hi all, I am using the following env vars:
> 
> ```
>     environment:
>       RUSTFS_ADDRESS: "0.0.0.0:9000"
>       RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
>       RUSTFS_EXTERNAL_ADDRESS: ":9000"
>       RUSTFS_CORS_ALLOWED_ORIGINS: "*"
>       RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
>       RUSTFS_CONSOLE_RATE_LIMIT_ENABLE: "true"
>       RUSTFS_CONSOLE_RATE_LIMIT_RPM: "60"
>       RUSTFS_CONSOLE_AUTH_TIMEOUT: "1800"
> ```
> 
> But I am unable to login, when I try to login via the UI console on port `:9001` It tries to make a POST request to the root and it returns a 405.
> 
> Can anyone advice?
> 
> Running on:
> 
> ```
> image:
>       repository: rustfs/rustfs
>       tag: 1.0.0-alpha.61
> ```
> 
> <img alt="Image" width="451" height="238" src="https://private-user-images.githubusercontent.com/42570659/497372828-4927d4a6-140a-4dab-8a6d-2efacc541d6c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk1ODczODUsIm5iZiI6MTc1OTU4NzA4NSwicGF0aCI6Ii80MjU3MDY1OS80OTczNzI4MjgtNDkyN2Q0YTYtMTQwYS00ZGFiLThhNmQtMmVmYWNjNTQxZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA0VDE0MTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZDNlMWQ5MjRkNjIzNGVmODczMzg1NzdiNjVjMjU2MmU0NTQzNzgyMDU4NDZkZTgyOTQ4ZTQxNTBhMjZlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OwaGO7-jf1zmSO4kPC9RQOo6NqHGmp8KoELlz6aXz4w">
> Many thanks

Please provide the relevant content of `http://localhost:9001/config.json` and the complete `docker-compose.yml` content. What is the port mapped by the `-p` parameter? Are they the default '9000:9000' and '9001:9001'? For example, if it is '9010:9000', then 'RUSTFS_EXTERNAL_ADDRESS=":9010"', thank you ~

Among them, the following `docker` command:
```shell
docker run -d --name rustfs59-1 -p 9159:9000 -p 9151:9001 -e RUSTFS_EXTERNAL_ADDRESS=":9159" rustfs/rustfs:1.0.0-alpha.61
```
The corresponding `config.json` (http://localhost:9151/config.json) content is as follows:
```json
{"api":{"baseURL":"http://localhost:9159/rustfs/admin/v3"},"s3":{"endpoint":"http://localhost:9159","region":"cn-east-1"},"release":{"version":"1.0.0-alpha.61","date":"2025-09-30T09:32:23Z"},"license":{"name":"Apache-2.0","url":"https://www.apache.org/licenses/LICENSE-2.0"},"doc":"https://rustfs.com/docs/"}
```

**Comment by loverustfs** [comment]
Due to front-end anomalies, we've recompiled alpha.61.

You can update to the latest alpha.61 to see if the login error persists.

@volfco @JaynLau @alexbaeza

**Comment by mreiche** [comment]
This error was still present in `rustfs:1.0.0-alpha.64` but fixed in `rustfs:1.0.0-alpha.83`
