### ISSUE TITLE
After the domain name is reversed, the bucket cannot be accessed and an error message is displayed.

### ISSUE THREAD

**Issue by BeeThor** [rustfs/rustfs#717]
容器docker-compose.yml配置
```
version: "3.8"

services:
  # RustFS main service
  rustfs:
    security_opt:
      - "no-new-privileges:true"
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    build:
      context: .
      dockerfile: Dockerfile.source
      args:
        TARGETPLATFORM: linux/amd64
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # Console port
    environment:
      - RUSTFS_VOLUMES=/data/rustfs0
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_EXTERNAL_ADDRESS=:9000  # Same as internal since no port mapping
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_LOG_LEVEL=info
    volumes:
      - deploy/data/pro:/data
      - deploy/logs:/app/logs
    networks:
      - rustfs-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

通过IP+9001正常访问后台、正常上传、下载文件。

但是使用两个域名ng反向代理9001、9000均出现进入存储桶报错No Such Bucket。尝试过使用一个域名反代，一样的点击存储桶就报错No Such Bucket。请帮看下是哪里的问题，如何实现一个域名同时支持web及s3。谢谢

```
    location / {
        proxy_pass http://127.0.0.1:9001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        client_max_body_size 0;
        proxy_buffering off;
    }
```

**Comment by loverustfs** [comment]
This is Nginx document, and we are re-test this configure.

https://docs.rustfs.com/integration/nginx.html

**Comment by BeeThor** [comment]
# The HEAD request returns 403, and the console cannot access the bucket.

## 🔧 Configure

### Docker port mapping
- Container port `9000` (S3 API) → Host port
- Container port `9001` (Console) → Host port

### Access Methods
- ✅ Direct access: `http://IP:hostport` → **Works normally**
- ✅ Access the console via domain name: `https://your-domain.com/rustfs/console/` → **Accessible**
- ❌ Click on the bucket in the console → **Error 403**

## 🚨 Problem Description

1. Configure domain name access to RustFS through Nginx reverse proxy
2. Access the console (/rustfs/console/) normally
3. Bucket list visible in the console
4. However, an error message appears when clicking on any bucket
5. Browser developer tools show a 403 error on a HEAD request


## 📊 Error message

### Browser console error

```
Failed to load resource: the server responded with a status of 403 ()
```

### Network Request Details

**Failed Request (HEAD Request):**
```
Request URL: https://your-domain.com/test/
Request Method: HEAD
Status Code: 403 Forbidden

Request Headers:
Authorization: AWS4-HMAC-SHA256 Credential=...
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20251025T025543Z

```

## 📄 Complete Nginx configuration (with desensitized domain names)
```

upstream rustfs_api {
    least_conn;
    server 127.0.0.1:9000;
    keepalive 32;
}

upstream rustfs_console {
    least_conn;
    server 127.0.0.1:9001;
    keepalive 32;
}

server
{
    listen 80;
    listen 443 ssl;
    listen 443 quic;
    http2 on;
    server_name your-domain.com;
    root /www/wwwroot/your_site;
    
    #CERT-APPLY-CHECK--START
    include /www/server/panel/vhost/nginx/well-known/your-domain.com.conf;
    #CERT-APPLY-CHECK--END
    
    # BT Configure
    include /www/server/panel/vhost/nginx/extension/your-domain.com/*.conf;
    
    #SSL-START  SSL Configure
    ssl_certificate    /www/server/panel/vhost/cert/your-domain.com/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/your-domain.com/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_tickets on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    add_header Alt-Svc 'quic=":443"; h3=":443"; h3-29=":443"; h3-27=":443";h3-25=":443"; h3-T050=":443"; h3-Q050=":443";h3-Q049=":443";h3-Q048=":443"; h3-Q046=":443"; h3-Q043=":443"';
    error_page 497  https://$host$request_uri;
    #SSL-END

    #ERROR-PAGE-START
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END

    #PHP-INFO-START
    #include enable-php-00.conf;
    #PHP-INFO-END

    #REWRITE-START
   # Note: Baota's rewrite rules may cause HEAD requests to return 403.
   # It is recommended to comment out the following line
    # include /www/server/panel/vhost/rewrite/your-domain.com.conf;
    #REWRITE-END

    #==================== RustFS dedicated configuration starts =====================
    
    # Allow uploading of large files (no limit)
    client_max_body_size 0;
    
    # Allow uploading of large files (no limit)
    proxy_buffering off;
    proxy_request_buffering off;
    
    # Allow special characters in headers (required by the S3 API)
    ignore_invalid_headers off;
    
    # Timeout configuration (suitable for uploading and downloading large files)
    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    proxy_read_timeout 300;
    
    # === RustFS Web Console ===
    # The highest priority, must be placed first
    # Path：https://your-domain.com/rustfs/console/
    location /rustfs/ {
        # Fix: Do not add /rustfs/ after proxy_pass to avoid path duplication
        proxy_pass http://rustfs_console;
        
        # Proxy headers configuration (use $http_host to retain port information)
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # HTTP/1.1 and WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # Timeout configuration (console operations may take a long time)
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
    }
    
    # === RustFS S3 API ===
    # Handles all S3 bucket requests (including HEAD, GET, PUT, DELETE, etc.)
    # 访问路径：https://your-domain.com/bucket-name/object-key
    location / {
        proxy_pass http://rustfs_api;
        
        # HTTP/1.1 support and keepalive
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # HTTP/1.1 support and keepalive
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        
        # Disable chunked transfer encoding
        chunked_transfer_encoding off;
        
        # Timeout configure
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
    }
    
    # ==================== RustFS  Configure end============

    # Files or directories that are prohibited from access
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    # SSL folder
    location ~ \.well-known{
        allow all;
    }

    # Do not place sensitive files in the certificate verification directory
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }
    
    # 日志配置
    access_log  /www/wwwlogs/your-domain.log;
    error_log  /www/wwwlogs/your-domain.error.log;
}

```

**Comment by loverustfs** [comment]
Okay, got it.
We will get back to you after the test is completed.

**Comment by loverustfs** [comment]
I deployed RustFS using the binary method.

Below is my Nginx configuration file. My forwarding and usage are all working correctly. See the screenshot:

<img width="2552" height="1590" alt="Image" src="https://github.com/user-attachments/assets/e088b36e-11bc-4c14-a691-8ea2d8f9502e" />


## Nginx vhost configure:

```
upstream rustfs {
   least_conn;
   server 127.0.0.1:3000;
}
server {
   listen       80;
   listen  [::]:80;
   server_name  testaa.rustfs.com;

   # Allow special characters in headers
   ignore_invalid_headers off;
   # Allow any size file to be uploaded.
   # Set to a value such as 1000m; to restrict file size to a specific value
   client_max_body_size 0;
   # Disable buffering
   proxy_buffering off;
   proxy_request_buffering off;

   location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_connect_timeout 300;
      # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      chunked_transfer_encoding off;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";




      proxy_pass http://rustfs; # This uses the upstream directive definition to load balance
   }
}

upstream rustfs-console {
   least_conn;
   server 127.0.0.1:30001;
}
server {
   listen       8080;
   listen  [::]:8080;
   server_name  testaa.rustfs.com;

   # Allow special characters in headers
   ignore_invalid_headers off;
   # Allow any size file to be uploaded.
   # Set to a value such as 1000m; to restrict file size to a specific value
   client_max_body_size 0;
   # Disable buffering
   proxy_buffering off;
   proxy_request_buffering off;

   location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_connect_timeout 300;
      # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      chunked_transfer_encoding off;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";




      proxy_pass http://rustfs-console; # This uses the upstream directive definition to load balance
   }
}
```

## RustFS configure:

```
RUSTFS_ACCESS_KEY=rustfsadmin
RUSTFS_SECRET_KEY=rustfsadmin
RUSTFS_VOLUMES="/data/rustfs0"
RUSTFS_ADDRESS=":3000"
RUSTFS_CONSOLE_ADDRESS=":30001"
RUSTFS_CONSOLE_ENABLE=true
RUST_LOG=warn
RUSTFS_OBS_LOG_DIRECTORY="/var/logs/rustfs/"
```

**Comment by loverustfs** [comment]
If you encounter an error you can't resolve, feel free to email me or contact me on Slack.

My email address is: hello@rustfs.com

**Comment by BeeThor** [comment]
After testing, I still encountered the same issue. When I clicked on any bucket, I got a "Bucket not found" error.
The IP and port numbers were all working correctly. The problem was the reverse domain name. No matter how I adjusted it, I still got an error when I clicked on the bucket.

**Comment by BeeThor** [comment]
I hope it can support configuring two domain names like minio, separate web and s3. Or change to a single port.

**Comment by loverustfs** [comment]
> I hope it can support configuring two domain names like minio, separate web and s3. Or change to a single port.

We will not change it to a single port. Many users have requested that we separate the Endpoint and Console like MinIO.

**Comment by loverustfs** [comment]
Otherwise, our configuration works fine.

RustFS endpoint 3000
RustFS console 30001

Nginx reverse proxy RustFS endpoint 8080 (http://testaa.rustfs.com:8080)
Nginx reverse proxy RustFS console 80 (http://testaa.rustfs.com)

<img width="2042" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a6c0d937-1b04-41d8-a3ff-0083c060eb63" />

**Comment by BeeThor** [comment]
Can the configuration file support dual domain name configuration, and separate ng proxy, completely separate, so that better control can be achieved?

**Comment by loverustfs** [comment]
Of course, we configured the IP address 8.217.249.37 and testaa.rustfs.com,  testbb.rustfs.com.

IP address:
8.217.249.37:3000
8.217.249.37:30001

Nginx:
8.217.249.37:80
8.217.249.37:8080

Domain name:

testaa.rustfs.com:30001 can access the console.
testaa.rustfs.com:3000 can access the endpoint.

testbb.rustfs.com:30001 can also access the console.
testbb.rustfs.com:3000 can also access the endpoint.

I don't understand your requirements.


## testbb.rustfs.com:30001
<img width="2502" height="1248" alt="Image" src="https://github.com/user-attachments/assets/6d6789a5-55e8-46e2-bb07-e4d224c1b0a1" />

## testaa.rustfs.com:30001
<img width="2220" height="1194" alt="Image" src="https://github.com/user-attachments/assets/1eb1dc4e-44c1-4721-b3d4-84424ea35a12" />


## 8.217.249.37:30001

<img width="1764" height="998" alt="Image" src="https://github.com/user-attachments/assets/19911687-7ea8-4445-b1c6-b7c8162e4a50" />


## Nginx reverse proxy : testaa.rustfs.com:80


<img width="2078" height="1328" alt="Image" src="https://github.com/user-attachments/assets/f9e604ab-0ebf-4070-b841-52c977e66517" />

**Comment by loverustfs** [comment]
I don't know your core needs, how can I help you.

**Comment by BeeThor** [comment]
因为采用docker或者二进制方式安装，都是IP+端口一切正常，但是只要ng域名反带，不管是一个域名，还是分为两个域名，都是在点击进入任一存储桶内部时报错  Bucket not found。也试过AI分析问题，尝试各种方案，均是出现该问题。

ng配置x1.domain.com 反代9001端口访问控制台；ng配置x2.domain.com反代9000端口s3服务。均是80和443端口，申请SSL证书，https访问。

相同的配置部署minio均为正常。


**English:**

When installing using Docker or binary, the IP and port numbers are all working fine. However, when using ng for reverse proxy, regardless of whether it's a single domain or two, I get the error "Bucket not found" when accessing any bucket. I've tried AI analysis and various solutions, but the same issue persists.

ng configures x1.domain.com to proxy port 9001 for console access; ng configures x2.domain.com to proxy port 9000 for the S3 service. Both use ports 80 and 443, apply for SSL certificates, and use HTTPS for access.

Deploying minio with the same configuration works fine.

**Comment by loverustfs** [comment]
> Of course, we configured the IP address 8.217.249.37 and testaa.rustfs.com, testbb.rustfs.com.
> 
> IP address: 8.217.249.37:3000 8.217.249.37:30001
> 
> Nginx: 8.217.249.37:80 8.217.249.37:8080
> 
> Domain name:
> 
> testaa.rustfs.com:30001 can access the console. testaa.rustfs.com:3000 can access the endpoint.
> 
> testbb.rustfs.com:30001 can also access the console. testbb.rustfs.com:3000 can also access the endpoint.
> 
> I don't understand your requirements.
> 
> ## testbb.rustfs.com:30001
> <img alt="Image" width="2000" height="1248" src="https://private-user-images.githubusercontent.com/155562731/505693763-6d6789a5-55e8-46e2-bb07-e4d224c1b0a1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE0NzI0NDQsIm5iZiI6MTc2MTQ3MjE0NCwicGF0aCI6Ii8xNTU1NjI3MzEvNTA1NjkzNzYzLTZkNjc4OWE1LTU1ZTgtNDZlMi1iYjA3LWU0ZDIyNGMxYjBhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyNlQwOTQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODI3ZjNkYTY5YzkxZWI0MzU5ODU3MjQyNzRkNjAyYmZkYTYyN2IwM2IzNmU5MjEzZmUxN2U1ZGE4ZmI5NGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GqvLGXDLiP7JVZWkSoOcdFBWxUf5Hv4j1QUiTRlJl8U">
> ## testaa.rustfs.com:30001
> <img alt="Image" width="2000" height="1194" src="https://private-user-images.githubusercontent.com/155562731/505693781-1eb1dc4e-44c1-4721-b3d4-84424ea35a12.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE0NzI0NDQsIm5iZiI6MTc2MTQ3MjE0NCwicGF0aCI6Ii8xNTU1NjI3MzEvNTA1NjkzNzgxLTFlYjFkYzRlLTQ0YzEtNDcyMS1iM2Q0LTg0NDI0ZWEzNWExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyNlQwOTQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDVkYzIyOWJkOGFjYjM0MzkyMTkzZDRjOTFjYjFmYzIxMmExNGQyYTdmZjQxMGZjNjEyMTgzNmVmNTMzOTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GAzffqF8hXptNjchT9AUaMAPowWraT4jmZtC3tFinH8">
> ## 8.217.249.37:30001
> <img alt="Image" width="1764" height="998" src="https://private-user-images.githubusercontent.com/155562731/505693835-19911687-7ea8-4445-b1c6-b7c8162e4a50.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE0NzI0NDQsIm5iZiI6MTc2MTQ3MjE0NCwicGF0aCI6Ii8xNTU1NjI3MzEvNTA1NjkzODM1LTE5OTExNjg3LTdlYTgtNDQ0NS1iMWM2LWI3YzgxNjJlNGE1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyNlQwOTQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDliMDMwMjEzZjhhMWIxNDI1MjM0ODYwOWY5Mzk0ODY4NTMxNTdiZDg0NGVmYWQ3NGZiMzAyMjI1YjVhY2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KRSvpSMCPO_TK0_7xf_LpPspwNev_8s3dAmfgyGQsgE">
> ## Nginx reverse proxy : testaa.rustfs.com:80
> <img alt="Image" width="2000" height="1328" src="https://private-user-images.githubusercontent.com/155562731/505693862-f9e604ab-0ebf-4070-b841-52c977e66517.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE0NzI0NDQsIm5iZiI6MTc2MTQ3MjE0NCwicGF0aCI6Ii8xNTU1NjI3MzEvNTA1NjkzODYyLWY5ZTYwNGFiLTBlYmYtNDA3MC1iODQxLTUyYzk3N2U2NjUxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyNlQwOTQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzZkYmI0YTI2MTMyYTg0OGExNmFhM2JlOTQ3ZTVmMDg0M2U0YjZmMDA5OWI0ZGVjNWVhYjNjZTE3NGUzMThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EMxUKBxt4puqhHctQX5XkeRDpbruDFBSDweImbANEuI">

Is our configuration different from yours?

**Comment by BeeThor** [comment]
Domain name without port access, such as oss.domain.com for accessing the console; s3.domain for the s3 API.

**Comment by loverustfs** [comment]
Of course you can. Did you see my configuration?
And did you test the demo URL I prepared?

**Comment by loverustfs** [comment]
Would you be able to share your email or preferred IM? We'd be happy to set up a Zoom call to help with any questions you have.

**Comment by BeeThor** [comment]
This is my newly created zoom channel. Please ask an engineer to join and help me check the problem. Thank you.

https://us05web.zoom.us/launch/chat/v2/eyJzaWQiOiI5MGE0OWVjZTk0MmY0YWNlYmM2ZGY0OGQ2MjM2ZWE3MkBjb25mZXJlbmNlLnhtcHAuem9vbS51cyJ9

**Comment by loverustfs** [comment]
Ah, that's a bummer. It looks like the add didn't go through. It might have already expired.
My email is hello@rustfs.com. Want to try connecting there instead?

<img width="890" height="226" alt="Image" src="https://github.com/user-attachments/assets/5f8dbaf3-bd82-4bd0-b641-f06344fe47b4" />

**Comment by BeeThor** [comment]
已对此邮箱发送邀请

**Comment by LyndonXiao** [comment]
可能是nginx配置问题，把控制台的路径改为 `location /`，然后把 S3 API 的路径改为 `location /api/`，试试呢？
如下图，默认rustfs控制台的接口路径里有`/rustfs/`，你的配置正好瞎猫撞死死耗子能进控制台，但是进入桶的接口是不带`/rustfs/`的所以异常了


This could be an Nginx configuration issue. Try changing the console path to location / and the S3 API path to location /api/.

As shown below, the default Rustfs console interface path includes /rustfs/. Your configuration is a bit of a fluke, allowing you to access the console. However, the bucket interface doesn't include /rustfs/, which is why the issue occurs.



<img width="1112" height="669" alt="Image" src="https://github.com/user-attachments/assets/fc2f8219-164c-4f5b-9686-d645317e05c5" />

**Comment by BeeThor** [comment]
经过测试，已解决此问题。
现象：域名反向代理后，进入存储桶报错Bucket not found
解决方案：需要在Nginx配置文件中添加

After testing, this issue has been resolved.
Symptom: After the domain name is reverse-proxyed, accessing the bucket displays the error "Bucket not found."
Solution: Add the following to the Nginx configuration file:

```
# Disable Nginx from converting HEAD to GET:contentReference[oaicite:4]{index=4}
proxy_cache_convert_head off;
```

How it works:
> By default, Nginx converts HEAD requests to GET requests for caching purposes, which invalidates S3 V4 signatures and results in 403 AccessDenied errors. The Nginx documentation indicates that this conversion can be disabled by setting proxy_cache_convert_head off.

Refer to Nginx official explanation:

<img width="823" height="190" alt="Image" src="https://github.com/user-attachments/assets/880e8690-361a-4785-b8e7-120896ef8853" />

**Comment by loverustfs** [comment]
Thank you very much.

**Comment by zK0G0w** [comment]
> 经过测试，已解决此问题。 现象：域名反向代理后，进入存储桶报错Bucket not found 解决方案：需要在Nginx配置文件中添加
> 
> After testing, this issue has been resolved.经过测试，该问题已经解决。 Symptom: After the domain name is reverse-proxyed, accessing the bucket displays the error "Bucket not found."现象：域名反向代理后，访问存储桶显示错误“找不到存储桶”。 Solution: Add the following to the Nginx configuration file:解决方法：在 Nginx 配置文件中添加以下内容：
> 
> ```
> # Disable Nginx from converting HEAD to GET:contentReference[oaicite:4]{index=4}
> proxy_cache_convert_head off;
> ```
> 
> How it works:其工作原理：
> 
> > By default, Nginx converts HEAD requests to GET requests for caching purposes, which invalidates S3 V4 signatures and results in 403 AccessDenied errors. The Nginx documentation indicates that this conversion can be disabled by setting proxy_cache_convert_head off.默认情况下，Nginx 会出于缓存原因将 HEAD 请求转换为 GET 请求，这会导致 S3 V4 签名失效，并引发 403 AccessDenied 错误。Nginx 文档指出，可以通过设置 proxy_cache_convert_head off 来禁用此转换。
> 
> Refer to Nginx official explanation:参考 Nginx 官方解释：
> 
> <img alt="Image" width="823" height="190" src="https://private-user-images.githubusercontent.com/73262891/506556937-880e8690-361a-4785-b8e7-120896ef8853.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM1MjQ0OTUsIm5iZiI6MTc2MzUyNDE5NSwicGF0aCI6Ii83MzI2Mjg5MS81MDY1NTY5MzctODgwZTg2OTAtMzYxYS00Nzg1LWI4ZTctMTIwODk2ZWY4ODUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE5VDAzNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDY3NzVlMTRhMzExNjZkMjUzZjM2MDYzODEyYTVmODBmMjQ1MzA5OTFlYzA2N2YzMzZkNzYxNzBjNzM5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8gd_UCGDKyIm_cRS5XrcWm1l3EFzREnukHn7aZB2EL0">

Thank you so much for your solution! Your advice perfectly resolved my problem.
