### ISSUE TITLE
cannot delete folder

### ISSUE THREAD

**Issue by cruvie** [rustfs/rustfs#768]
is there anyway to delete folder(empty) by aws sdk?

```go
import (
	"bytes"
	"context"
	"errors"
	"log"
	"testing"

	"gitee.com/cruvie/kk_go_kit/kk_stage"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/credentials"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
)
func TestDeleteObject(t *testing.T) {
	objects := []DeleteObjectInput{
		{
			BucketName: "ccc",
			ObjectName: "fafafa",
		},
		{
			BucketName: "ccc",
			ObjectName: "fafafa/",
		},
	}
	for _, object := range objects {
		DeleteObject(object)
	}
	
}

type DeleteObjectInput struct {
	BucketName string
	ObjectName string
}

func DeleteObject(input DeleteObjectInput) (err error) {
	cfg := aws.Config{
		Region:       "c.Region",
		BaseEndpoint: aws.String("http://127.0.0.1:9000"),
		Credentials:  aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider("", "", "")),
	}

	S3Client := s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.UsePathStyle = true
	})
	if input.BucketName == "" || input.ObjectName == "" {
		return errors.New("required parameter is empty")
	}

	_, err = S3Client.DeleteObject(context.Background(), &s3.DeleteObjectInput{
		Bucket: &input.BucketName,
		Key:    &input.ObjectName,
	})

	if err != nil {
		return err
	}

	return nil
}
```
after the test, the folder still exists
<img width="1400" height="664" alt="Image" src="https://github.com/user-attachments/assets/2ff9dec4-3bf6-4ba3-8f7a-6fb03af9f273" />

**Comment by cruvie** [comment]
FYI in minio after delete the last object in a folder, the empty folder will be deleted as well.(also by aws sdk)

**Comment by loverustfs** [comment]
Hey  @weisd ,
This may also be related to the following issue:
https://github.com/rustfs/rustfs/issues/731

**Comment by Howietron** [comment]
我好像也出现过这问题，我是通过S3api创建的桶，从web页面没法删除，只能通过api进行删除

**Comment by weisd** [comment]
@cruvie  Hi, do you have version control enabled?

**Comment by cruvie** [comment]
@weisd no

**Comment by weisd** [comment]
@cruvie Could you please share your putObject code?

**Comment by cruvie** [comment]
@weisd here https://github.com/rustfs/rustfs/issues/766

**Comment by loverustfs** [comment]
Hi @cruvie ,

We've patched this bug in the latest release. Could you please update and let us know if that fixes it for you?

If you're all set, you can go ahead and close this issue. If not, just comment here, and we'll be happy to take another look.

Thanks!

**Comment by Morethanevil** [comment]
Hi @loverustfs I have the same issue with alpha 67. I just tried it with the web UI. I get the message "Successful" but it is still there

![Image](https://github.com/user-attachments/assets/d2ae01ec-beb4-4bbf-8e77-ad78372f6e2f)

**Comment by cruvie** [comment]
@loverustfs issue still exists with the latest docker image build 2 days ago

**Comment by loverustfs** [comment]
Hey @cruvie @Morethanevil ,

Everything worked fine on our end. Could you please tell me what your steps were?

**Comment by Morethanevil** [comment]
I copied a folder as a backuo into an empty bucjet with versioning enabled. Does not matter if API or web UI. This folder has a few subfolders. 

I then deleted the folder, the files were removed, but the folders remain empty. You see in my Screenshot "delete successful". I tried to refresh the page.


Maybe they are still shown because of the versioning 🤔

**Comment by loverustfs** [comment]
> I copied a folder as a backuo into an empty bucjet with versioning enabled. Does not matter if API or web UI. This folder has a few subfolders.
> 
> I then deleted the folder, the files were removed, but the folders remain empty. You see in my Screenshot "delete successful". I tried to refresh the page.
> 
> Maybe they are still shown because of the versioning 🤔

Hi @weisd ,

Perhaps this bug hasn't been fixed yet.

**Comment by Morethanevil** [comment]
I tried a few approaches and I found a solution for me. It is the versioning that prevents disappearing folders after deleting. I checked the same behavior with MinIO too.

1. Create a bucket with versioning
2. Upload a folder with subfolders and or files
3. Delete the same folder, it still appears even on MinIO

This is normal, since MinIO only removes **empty** folders, but the folder is not empty, it contains deleted files.

MinIO did have a solution on the web UI for this:

<img width="2450" height="215" alt="Image" src="https://github.com/user-attachments/assets/6075f079-9df9-413e-b114-7feceffea3d3" />

With this MinIO shows deleted objects too, which then can be deleted completely.

A second function of MinIO is to delete ALL versions when removing a file / folder:

<img width="896" height="407" alt="Image" src="https://github.com/user-attachments/assets/529782cc-0c98-4a86-be0f-ced185160e9b" />

It would be awesome if RustFS would get those features too. For the moment I only can delete all versions via MC.
For anyone wanting to the same here is the command, but be careful, use `--dry-run` first to see what it deletes:

To fully wipe the bucket:
`mc rm ALIAS/BUCKET --versions --force --recursive --dry-run`

Only delete a folder inside the bucket:
`mc rm ALIAS/BUCKET/PATH/TO/FOLDER --versions --force --recursive --dry-run`

Remove `--dry-run` after checking the result.

`--versions` means including all versions
`--recursive` means include subfolders
`--force` is needed because of `--recursive`
`--dry-run` is dry run, only show what would happen

**Comment by loverustfs** [comment]
> I tried a few approaches and I found a solution for me. It is the versioning that prevents disappearing folders after deleting. I checked the same behavior with MinIO too.
> 
> 1. Create a bucket with versioning
> 2. Upload a folder with subfolders and or files
> 3. Delete the same folder, it still appears even on MinIO
> 
> This is normal, since MinIO only removes **empty** folders, but the folder is not empty, it contains deleted files.
> 
> MinIO did have a solution on the web UI for this:
> 
> <img width="2450" height="215" alt="Image" src="https://github.com/user-attachments/assets/6075f079-9df9-413e-b114-7feceffea3d3" />
> 
> With this MinIO shows deleted objects too, which then can be deleted completely.
> 
> A second function of MinIO is to delete ALL versions when removing a file / folder:
> 
> <img width="896" height="407" alt="Image" src="https://github.com/user-attachments/assets/529782cc-0c98-4a86-be0f-ced185160e9b" />
> 
> It would be awesome if RustFS would get those features too. For the moment I only can delete all versions via MC.
> For anyone wanting to the same here is the command, but be careful, use `--dry-run` first to see what it deletes:
> 
> To fully wipe the bucket:
> `mc rm ALIAS/BUCKET --versions --force --recursive --dry-run`
> 
> Only delete a folder inside the bucket:
> `mc rm ALIAS/BUCKET/PATH/TO/FOLDER --versions --force --recursive --dry-run`
> 
> Remove `--dry-run` after checking the result.
> 
> `--versions` means including all versions
> `--recursive` means include subfolders
> `--force` is needed because of `--recursive`
> `--dry-run` is dry run, only show what would happen


@overtrue @cxymds 

I think this idea is  amazing.
Can our frontend implement this feature?

**Comment by loverustfs** [comment]
Hey @Morethanevil ,

Thank you for your suggestion!
We will resolve this issue through this PR.

https://github.com/rustfs/rustfs/pull/882

**Comment by cruvie** [comment]
@loverustfs in aws S3. 

```
Deletion behavior – When you delete an object in a directory bucket, 
Amazon S3 recursively deletes any empty directories in the object path. 
For example, if you delete the object key dir1/dir2/file1.txt, Amazon S3 deletes file1.txt.
 If the dir1/ and dir2/ directories are empty and contain no other objects, Amazon S3 also deletes those directories.
```

https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-express-differences.html

**Comment by Morethanevil** [comment]
Installed alpha 69, but I don't see an option to view deleted objects. There is no option to delete all versions when deleting a file / folder.

<img width="2996" height="1391" alt="Image" src="https://github.com/user-attachments/assets/6b3584db-95b3-4de0-b303-1900e0dadb14" />

```bash
rustfs 1.0.0-alpha.69
build time   : 2025-11-20 01:01:37 +00:00
build profile: release
build os     : linux-x86_64
rust version : rustc 1.91.1 (ed61e7d7e 2025-11-07)
rust channel : stable-x86_64-unknown-linux-gnu
git branch   :
git commit   : b73ca0220e264f97c2908f49f331cfb0b4b21f01
git tag      : 1.0.0-alpha.69
git status   :
```

**Comment by loverustfs** [comment]
Hey @cxymds ,
When can options be added to the front end?

**Comment by cxymds** [comment]
> Installed alpha 69, but I don't see an option to view deleted objects. There is no option to delete all versions when deleting a file / folder.
> 
> <img alt="Image" width="2000" height="1391" src="https://private-user-images.githubusercontent.com/110860055/516751695-6b3584db-95b3-4de0-b303-1900e0dadb14.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2MzI0NjMsIm5iZiI6MTc2MzYzMjE2MywicGF0aCI6Ii8xMTA4NjAwNTUvNTE2NzUxNjk1LTZiMzU4NGRiLTk1YjMtNGRlMC1iMzAzLTE5MDBlMGRhZGIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyMFQwOTQ5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWY0NzU0YTU4ZjllYjZlYmFiOWUyN2VmOGIwOTA0NWFjN2E2ZjMxZTNmNDQ0OTlmZTBjMzkwY2ZmMTA2NTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BvfYrHZiTAUaNpdPM0JqKdxUfw7SSySobor8JeS8nb8">
> rustfs 1.0.0-alpha.69
> build time   : 2025-11-20 01:01:37 +00:00
> build profile: release
> build os     : linux-x86_64
> rust version : rustc 1.91.1 (ed61e7d7e 2025-11-07)
> rust channel : stable-x86_64-unknown-linux-gnu
> git branch   :
> git commit   : b73ca0220e264f97c2908f49f331cfb0b4b21f01
> git tag      : 1.0.0-alpha.69
> git status   :

The file deletion list is already in the feature list and will be implemented soon. It is expected to be supported in the next release.

**Comment by Morethanevil** [comment]
Ahhh okay, I thought it was already included. I read about it in the release notes. Thanks for clarification 👍🏻

**Comment by cxymds** [comment]
> out it in th



> Ahhh okay, I thought it was already included. I read about it in the release notes. Thanks for clarification 👍🏻

Yes, this part has been implemented in the backend, but the console has not yet added interaction.And the good news is that this part was also available yesterday.

**Comment by lsl330** [comment]
Deletion does indeed have issues.

Version 69: Files cannot be deleted on the webpage; they remain even after deletion.

After deleting a file via the API, the file still exists on the webpage, but it cannot be downloaded via the API again (although the file can still be listed).

Files can be overwritten by uploading.

I didn't have this problem with version 65.

**Comment by loverustfs** [comment]
> I tried a few approaches and I found a solution for me. It is the versioning that prevents disappearing folders after deleting. I checked the same behavior with MinIO too.
> 
> 1. Create a bucket with versioning
> 2. Upload a folder with subfolders and or files
> 3. Delete the same folder, it still appears even on MinIO
> 
> This is normal, since MinIO only removes **empty** folders, but the folder is not empty, it contains deleted files.
> 
> MinIO did have a solution on the web UI for this:
> 
> <img alt="Image" width="2000" height="215" src="https://private-user-images.githubusercontent.com/110860055/513883647-6075f079-9df9-413e-b114-7feceffea3d3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM3NzYyODIsIm5iZiI6MTc2Mzc3NTk4MiwicGF0aCI6Ii8xMTA4NjAwNTUvNTEzODgzNjQ3LTYwNzVmMDc5LTlkZjktNDEzZS1iMTE0LTdmZWNlZmZlYTNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyMlQwMTQ2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDMwOGJlMWVmYTdiZTkzNDg2ZmIxNTlmZGYxMmM0MGI4OTAxODQwNmFiMjY1MTY0ZmMyYWFkMzBhOTZjY2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-NGtzfwpGxYRiMbES4HlS5E40qBEN5_IrOUzRZTQk_8">
> With this MinIO shows deleted objects too, which then can be deleted completely.
> 
> A second function of MinIO is to delete ALL versions when removing a file / folder:
> 
> <img alt="Image" width="896" height="407" src="https://private-user-images.githubusercontent.com/110860055/513884201-529782cc-0c98-4a86-be0f-ced185160e9b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM3NzYyODIsIm5iZiI6MTc2Mzc3NTk4MiwicGF0aCI6Ii8xMTA4NjAwNTUvNTEzODg0MjAxLTUyOTc4MmNjLTBjOTgtNGE4Ni1iZTBmLWNlZDE4NTE2MGU5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyMlQwMTQ2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTEwMzBmZjQzODE1ZWU5ZTEyNGMyNjA1NDkyZjBiNmEzN2Y0Y2UxODAxODJmZGVlMTc0ZTQ5MWVkYzQzNzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u1yhplsqkB0ymEzP07DjXIoCgmmUc7QsewqXco3cKY4">
> It would be awesome if RustFS would get those features too. For the moment I only can delete all versions via MC. For anyone wanting to the same here is the command, but be careful, use `--dry-run` first to see what it deletes:
> 
> To fully wipe the bucket: `mc rm ALIAS/BUCKET --versions --force --recursive --dry-run`
> 
> Only delete a folder inside the bucket: `mc rm ALIAS/BUCKET/PATH/TO/FOLDER --versions --force --recursive --dry-run`
> 
> Remove `--dry-run` after checking the result.
> 
> `--versions` means including all versions `--recursive` means include subfolders `--force` is needed because of `--recursive` `--dry-run` is dry run, only show what would happen

@lsl330 We adopted this suggestion.

This is not a deletion bug. Version control being enabled hides deleted versions; the data actually exists.

Therefore, deletion is impossible.

**Comment by lsl330** [comment]
> > 我尝试了几种方法，找到了适合自己的方案。它是版本控制，防止删除后文件夹消失。我也用 MinIO 测试了同样的行为。
> > 
> > 1. 创建一个带有版本控制的桶
> > 2. 上传一个包含子文件夹和/或文件的文件夹
> > 3. 删除同一个文件夹，它即使在 MinIO 上依然显示
> > 
> > 这是正常的，因为MinIO只删除**空**文件夹，但这个文件夹不是空的，而是包含已删除的文件。
> > MinIO 确实在网页界面上有一个解决方案：
> > <img alt="图像" width="2000" height="215" src="https://private-user-images.githubusercontent.com/110860055/513883647-6075f079-9df9-413e-b114-7feceffea3d3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM3NzYyODIsIm5iZiI6MTc2Mzc3NTk4MiwicGF0aCI6Ii8xMTA4NjAwNTUvNTEzODgzNjQ3LTYwNzVmMDc5LTlkZjktNDEzZS1iMTE0LTdmZWNlZmZlYTNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyMlQwMTQ2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDMwOGJlMWVmYTdiZTkzNDg2ZmIxNTlmZGYxMmM0MGI4OTAxODQwNmFiMjY1MTY0ZmMyYWFkMzBhOTZjY2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-NGtzfwpGxYRiMbES4HlS5E40qBEN5_IrOUzRZTQk_8">通过这种方式，MinIO 也会显示已删除的对象，然后可以完全删除这些对象。MinIO 的第二个功能是在删除文件/文件夹时删除所有版本：
> > <img alt="图像" width="896" height="407" src="https://private-user-images.githubusercontent.com/110860055/513884201-529782cc-0c98-4a86-be0f-ced185160e9b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM3NzYyODIsIm5iZiI6MTc2Mzc3NTk4MiwicGF0aCI6Ii8xMTA4NjAwNTUvNTEzODg0MjAxLTUyOTc4MmNjLTBjOTgtNGE4Ni1iZTBmLWNlZDE4NTE2MGU5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyMlQwMTQ2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTEwMzBmZjQzODE1ZWU5ZTEyNGMyNjA1NDkyZjBiNmEzN2Y0Y2UxODAxODJmZGVlMTc0ZTQ5MWVkYzQzNzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u1yhplsqkB0ymEzP07DjXIoCgmmUc7QsewqXco3cKY4">如果RustFS也能获得这些功能，那就太棒了。目前我只能通过MC删除所有版本。对于想做同样作的人，这里有命令，但要小心，先用“---dry run”看看它删除了什么：要彻底擦拭桶：`mc rm ALIAS/BUCKET --versions --force --recursive --dry-run`
> > 只删除桶内的一个文件夹：`mc rm ALIAS/BUCKET/PATH/TO/FOLDER --versions --force --recursive --dry-run`
> > 检查结果后取出。`--dry-run`
> > `--versions`意味着包含所有版本意味着需要包含子文件夹，因为这是预演，只展示会发生什么`--recursive``--force``--recursive``--dry-run`
> 
> 我们采纳了这个建议。
> 
> 这不是删除的错误。启用版本控制会隐藏已删除的版本;数据确实存在。
> 
> 因此，删除是不可能的。

No, the existing solution is completely different.

Deleting a file on the web interface shows successful deletion, but the file still exists.

The API can retrieve the list, but cannot download it, while the web interface can download it.

If deleted versions are hidden,

then the API shouldn't retrieve deleted file entries when retrieving the list.

Also, I don't think I've enabled version control.

**Comment by loverustfs** [comment]
Really? Can you post the `mc` command and the steps you used? We'll run the test again.

**Comment by lsl330** [comment]
> Really? Can you post the mc command and the steps you used? We'll run the test again.

```
# docker exec -it rustfs-server /bin/sh
/ $ mc rm ALIAS/BUCKET/cloudsave/play0001 --versions --force --recursive --dry-run
/bin/sh: mc: not found
```

**Comment by loverustfs** [comment]
Hey @lsl330 ,

I think you haven't installed `mc`.

**Comment by lsl330** [comment]
> Hey [@lsl330](https://github.com/lsl330) ,
> 
> I think you haven't installed `mc`.

[root@VM-0-15-opencloudos ~]# mc rm rustfs/cloudsave/player0001 --versions --force --recursive --dry-run
DRYRUN: Removing `rustfs/cloudsave/player0001/2417-Save_6.sav` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:05 UTC).
DRYRUN: Removing `rustfs/cloudsave/player0001/records.dat` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:17 UTC).
[root@VM-0-15-opencloudos ~]# mc rm rustfs/cloudsave/player0001 --versions --force --recursive --dry-run
DRYRUN: Removing `rustfs/cloudsave/player0001/2417-Save_6.sav` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:05 UTC).
DRYRUN: Removing `rustfs/cloudsave/player0001/records.dat` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:17 UTC).
[root@VM-0-15-opencloudos ~]# mc rm rustfs/cloudsave/player0001 --versions --force --recursive --dry-run
DRYRUN: Removing `rustfs/cloudsave/player0001/2417-Save_6.sav` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:05 UTC).
DRYRUN: Removing `rustfs/cloudsave/player0001/records.dat` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:17 UTC).
[root@VM-0-15-opencloudos ~]# mc rm rustfs/cloudsave/player0001 --versions --force --recursive --dry-run
DRYRUN: Removing `rustfs/cloudsave/player0001/2417-Save_6.sav` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:05 UTC).
DRYRUN: Removing `rustfs/cloudsave/player0001/records.dat` (versionId=00000000-0000-0000-0000-000000000000) (modTime=2025-11-22 06:55:17 UTC).
[root@VM-0-15-opencloudos ~]# mc rm rustfs/cloudsave/player0001 --versions --force --recursive
Removed `rustfs/cloudsave/player0001/2417-Save_6.sav` (versionId=00000000-0000-0000-0000-000000000000).
Removed `rustfs/cloudsave/player0001/records.dat` (versionId=00000000-0000-0000-0000-000000000000).

This should be more intuitive, right?

Using `mc rm rustfs/cloudsave/player0001 --versions --force --recursive` deletes files.

However, using `mc rm rustfs/cloudsave/player0001 --versions --force --recursive --dry-run` fails to delete (files are listed and downloaded normally).

But it feels somewhat different from deleting via a browser or API. Files can be listed, but downloading results in an error (the ETag is retrieved correctly, but the file size is 0; a 0KB file with the same name can also be downloaded via a web browser).

**Comment by lsl330** [comment]
> Hey [@lsl330](https://github.com/lsl330) ,
> 
> I think you haven't installed `mc`.

After repeatedly deleting and creating buckets multiple times, it seems to be working normally. I'm not sure if it's related to the version migration. I'll report back if any further issues arise.

**Comment by loverustfs** [comment]
> > Hey [@lsl330](https://github.com/lsl330) ,
> > I think you haven't installed `mc`.
> 
> After repeatedly deleting and creating buckets multiple times, it seems to be working normally. I'm not sure if it's related to the version migration. I'll report back if any further issues arise.

Ok

**Comment by lsl330** [comment]
> > > Hey [@lsl330](https://github.com/lsl330) ,
> > > I think you haven't installed `mc`.
> > 
> > 
> > After repeatedly deleting and creating buckets multiple times, it seems to be working normally. I'm not sure if it's related to the version migration. I'll report back if any further issues arise.
> 
> Ok

The problem seems to be that the version control bucket is not enabled; enabling version control buckets works normally.

**Comment by loverustfs** [comment]
Hey @Morethanevil ,
Thank you for your suggestion.

@Howietron @lsl330 @cruvie 

We've added a "Show Deleted Objects" option to the interface, and the logic should be working correctly now.
I'm closing this issue for now. If you're still encountering bugs, please leave a comment and we'll reopen it.

<img width="2900" height="1394" alt="Image" src="https://github.com/user-attachments/assets/3871d60e-f378-4932-8188-c64161f1d5ee" />

**Comment by Morethanevil** [comment]
@loverustfs 
I tried out the new feature, it shows deleted objects yes, thanks :)

Two more things: If I show deleted objects and delete them again, all versions of the file / folder should be removed. It is not possible to delete all versions at once when I open the delete dialog. The only way to fully remove files and folders including all their versions is MinIO client at the moment.

Second: Deleted objects should have another color palette (grey or a light red tone), it would be easier to find them in larger file collections

**Comment by loverustfs** [comment]
> [@loverustfs](https://github.com/loverustfs) I tried out the new feature, it shows deleted objects yes, thanks :)
> 
> Two more things: If I show deleted objects and delete them again, all versions of the file / folder should be removed. It is not possible to delete all versions at once when I open the delete dialog. The only way to fully remove files and folders including all their versions is MinIO client at the moment.
> 
> Second: Deleted objects should have another color palette (grey or a light red tone), it would be easier to find them in larger file collections

Hey @cxymds @overtrue ,

Do you have better solutions?

**Comment by yaneony** [comment]
Folders are still not deleted in version 1.0.0-alpha.70.

**Comment by loverustfs** [comment]
> Folders are still not deleted in version 1.0.0-alpha.70.

What are your  steps?

**Comment by yaneony** [comment]
> > Folders are still not deleted in version 1.0.0-alpha.70.
> 
> What are your steps?

Click on delete right to the folder (in UI). Files are deleted, including files in subfolders, all folders and subfolders are still there.

**Comment by loverustfs** [comment]
> > > Folders are still not deleted in version 1.0.0-alpha.70.
> > 
> > 
> > What are your steps?
> 
> Click on delete right to the folder (in UI). Files are deleted, including files in subfolders, all folders and subfolders are still there.

We will try to reproduce this behavior to investigate the root cause. Could you please open a separate issue for this? We recommend adhering to a "one issue per bug" policy for better tracking.

As a temporary workaround, you can use mc or other S3-compatible command-line tools (such as s3cmd) to delete the folders.

**Comment by cruvie** [comment]
@loverustfs not fixed yet

<img width="3026" height="2012" alt="Image" src="https://github.com/user-attachments/assets/4c2494e1-117f-4bda-bf9a-faae97d7b74b" />

pls look back to the original issue

> is there anyway to delete folder(empty) by aws sdk?

and pls don't ignore 

> FYI in minio after delete the last object in a folder, the empty folder will be deleted as well.(also by aws sdk)

> https://github.com/rustfs/rustfs/issues/768#issuecomment-3550520939

kind remind, you'd better track different feat/bug in separated issues

**Comment by loverustfs** [comment]
Reopen this issue.

**Comment by soakes** [comment]
Yes, this issue is still present. The problem manifests as empty directories accumulating in buckets over time—files are deleted correctly, but their parent directories remain, creating an increasingly bloated bucket structure.

## Root Cause

The purge jobs are not functioning as intended. They remove the files within backup directories but fail to delete the now-empty parent directories themselves. This behavior works correctly with other S3 providers (AWS, Hetzner, GCP, DigitalOcean, IDrive, etc.) but fails consistently with RustFS.

## Concrete Example

Here's a real-world example from my `phpipam-k8s-sql-backup-prod` bucket showing the issue:

```
❯ mc tree --files rustfs/phpipam-k8s-sql-backup-prod
rustfs/phpipam-k8s-sql-backup-prod
├─ phpipam_20251121.033800          [empty - should be deleted]
├─ phpipam_20251122.033800          [empty - should be deleted]
├─ phpipam_20251123.033800          [empty - should be deleted]
├─ phpipam_20251124.033800          [empty - should be deleted]
├─ phpipam_20251125.033800
│  ├─ db_mysql-grant_20251125.sql.gz
│  ├─ db_performance_schema_20251125.sql.gz
│  ├─ db_phpipam_20251125.sql.gz
│  └─ db_sys_20251125.sql.gz
├─ phpipam_20251126.033800
│  ├─ db_mysql-grant_20251126.sql.gz
│  ├─ db_performance_schema_20251126.sql.gz
│  ├─ db_phpipam_20251126.sql.gz
│  └─ db_sys_20251126.sql.gz
├─ phpipam_20251127.033800
│  ├─ db_mysql-grant_20251127.sql.gz
│  ├─ db_performance_schema_20251127.sql.gz
│  ├─ db_phpipam_20251127.sql.gz
│  └─ db_sys_20251127.sql.gz
├─ phpipam_20251128.033800
│  ├─ db_mysql-grant_20251128.sql.gz
│  ├─ db_performance_schema_20251128.sql.gz
│  ├─ db_phpipam_20251128.sql.gz
│  └─ db_sys_20251128.sql.gz
├─ phpipam_20251129.033800
│  ├─ db_mysql-grant_20251129.sql.gz
│  ├─ db_performance_schema_20251129.sql.gz
│  ├─ db_phpipam_20251129.sql.gz
│  └─ db_sys_20251129.sql.gz
├─ phpipam_20251130.033800
│  ├─ db_mysql-grant_20251130.sql.gz
│  ├─ db_performance_schema_20251130.sql.gz
│  ├─ db_phpipam_20251130.sql.gz
│  └─ db_sys_20251130.sql.gz
├─ phpipam_20251201.033800
│  ├─ db_mysql-grant_20251201.sql.gz
│  ├─ db_performance_schema_20251201.sql.gz
│  ├─ db_phpipam_20251201.sql.gz
│  └─ db_sys_20251201.sql.gz
├─ phpipam_20251202.033800
│  ├─ db_mysql-grant_20251202.sql.gz
│  ├─ db_performance_schema_20251202.sql.gz
│  ├─ db_phpipam_20251202.sql.gz
│  └─ db_sys_20251202.sql.gz
├─ phpipam_20251203.033800
│  ├─ db_mysql-grant_20251203.sql.gz
│  ├─ db_performance_schema_20251203.sql.gz
│  ├─ db_phpipam_20251203.sql.gz
│  └─ db_sys_20251203.sql.gz
├─ phpipam_20251204.033800
│  ├─ db_mysql-grant_20251204.sql.gz
│  ├─ db_performance_schema_20251204.sql.gz
│  ├─ db_phpipam_20251204.sql.gz
│  └─ db_sys_20251204.sql.gz
├─ phpipam_20251205.033800
│  ├─ db_mysql-grant_20251205.sql.gz
│  ├─ db_performance_schema_20251205.sql.gz
│  ├─ db_phpipam_20251205.sql.gz
│  └─ db_sys_20251205.sql.gz
├─ phpipam_20251206.033800
│  ├─ db_mysql-grant_20251206.sql.gz
│  ├─ db_performance_schema_20251206.sql.gz
│  ├─ db_phpipam_20251206.sql.gz
│  └─ db_sys_20251206.sql.gz
├─ phpipam_20251207.033800
│  ├─ db_mysql-grant_20251207.sql.gz
│  ├─ db_performance_schema_20251207.sql.gz
│  ├─ db_phpipam_20251207.sql.gz
│  └─ db_sys_20251207.sql.gz
└─ phpipam_20251208.033800
   ├─ db_mysql-grant_20251208.sql.gz
   ├─ db_performance_schema_20251208.sql.gz
   ├─ db_phpipam_20251208.sql.gz
   └─ db_sys_20251208.sql.gz
```

The empty directories (20251121-20251124) should have been automatically cleaned up when their contents were purged.

## Impact & Severity

This is a critical issue with several downstream consequences:

- **Bucket clutter**: Buckets accumulate empty directories over time, making them difficult to manage and monitor
- **Bloated namespace**: Directory listings become increasingly unwieldy as the bucket ages
- **Bucket deletion failure**: Buckets containing orphaned directories cannot be deleted, even if empty
- **Application incompatibility**: Applications like Seafile that require exact directory structures cannot reliably use RustFS as a backend

I've temporarily migrated critical S3 workloads to Cloudflare pending a resolution, but this significantly limits RustFS's viability for production backup and archival scenarios.

**Comment by soakes** [comment]
@loverustfs 

Ref the below...

> As a temporary workaround, you can use mc or other S3-compatible command-line tools (such as s3cmd) to delete the folders.

This does not work, this is how my backup scripts works by using `minio mc`, even doing manaully using `mc` fails as can be seen below.

```
# Remove the empty directory recursively with force flag
❯ mc rm --recursive --force rustfs/phpipam-k8s-sql-backup-prod/phpipam_20251121.033800

# Attempt to list the directory to confirm deletion
❯ mc ls rustfs/phpipam-k8s-sql-backup-prod/phpipam_20251121.033800/

# Search for the directory in the bucket listing
❯ mc ls rustfs/phpipam-k8s-sql-backup-prod/|grep phpipam_20251121.033800

# Output: Directory still exists with 0 bytes despite deletion attempt
[2025-12-08 20:16:37 GMT]     0B phpipam_20251121.033800/
```

Below is how it should behave:

```
 ❯ mc tree --files cloudflare/testbucket
cloudflare/testbucket
└─ testdir
   └─ testfile

~
 ❯ mc rm --recursive --force cloudflare/testbucket/testdir

Removed `cloudflare/testbucket/testdir`.
Removed `cloudflare/testbucket/testdir/testfile`.

~
 ❯ mc tree --files cloudflare/testbucket

~
 ❯ mc ls cloudflare/testbucket/|grep testdir
```

**Comment by loverustfs** [comment]
Hey @weisd  @houseme ,

Could we prioritize fixing this bug?

**Comment by soakes** [comment]
Hi @loverustfs,

I have done some testing this morning to try and help and see whats really going on, below is what ive found and hope it can help your team to fix the issues.

---

# Bug Fix: Versioning Control Deletion Issue

## Summary

After investigating further, I believe iv'e identified the root cause of the deletion issue. The problem stems from **bucket versioning state management** rather than the deletion mechanism itself.

## Root Cause Analysis

### The Issue

When versioning control is enabled on a bucket (or has been previously enabled and then disabled), the `mc rm` command creates delete markers instead of performing actual deletions. This persists even after versioning is explicitly disabled, rendering the bucket unable to be cleaned up properly.

### Key Finding

The core problem is that **enabling/disabling versioning isn't properly resetting the bucket's internal state**. Once versioning is enabled, disabling it later doesn't clear the versioning markers, causing the deletion behavior to remain corrupted.

## Evidence and Test Cases

### Test Case 1: Fresh Bucket (No Versioning)

✅ **Works correctly**

```bash
~/minio
❯ mc ls rustfs-backup/testbucket/phpipam_20251116.034800/
[2025-12-09 10:08:57 GMT]   102B STANDARD phpipam_data_20251116.tar.gz

~/minio
❯ mc rm --force --recursive rustfs-backup/testbucket/phpipam_20251116.034800/
Removed `rustfs-backup/testbucket/phpipam_20251116.034800/phpipam_data_20251116.tar.gz`.

~/minio
❯ mc ls rustfs-backup/testbucket/|grep phpipam_20251116.034800/
```

**Result:** Object deleted successfully. No delete markers created.

### Test Case 2: Bucket with Versioning Enabled

❌ **Fails - creates delete markers**

```bash
~/minio
❯ mc ls rustfs-backup/testbucket/phpipam_20251117.034800/
[2025-12-09 10:08:57 GMT]   102B STANDARD phpipam_data_20251117.tar.gz

~/minio
❯ mc rm --force --recursive rustfs-backup/testbucket/phpipam_20251117.034800/
Created delete marker `rustfs-backup/testbucket/phpipam_20251117.034800/phpipam_data_20251117.tar.gz` (versionId=6003c1f1-6de8-41ba-91d6-bf381bbadc9a).

~/minio
❯ mc ls rustfs-backup/testbucket/|grep phpipam_20251117.034800/
[2025-12-09 10:11:54 GMT]     0B phpipam_20251117.034800/
```

**Result:** Delete markers persist; directory still visible.

### Test Case 3: Bucket with Versioning Disabled (After Being Enabled)

❌ **Still fails - problem persists**

```bash
~/minio
❯ mc rm --force --recursive rustfs-backup/testbucket/phpipam_20251117.034800/
Created delete marker `rustfs-backup/testbucket/phpipam_20251117.034800/phpipam_data_20251117.tar.gz`.

~/minio
❯ mc ls rustfs-backup/testbucket/|grep phpipam_20251117.034800/
[2025-12-09 10:13:04 GMT]     0B phpipam_20251117.034800/
```

**Result:** Even with versioning disabled, delete markers are still created. The bucket is now permanently unable to clean up objects.

## Impact

- **New buckets without versioning:** Work correctly ✅
- **Buckets with versioning enabled:** Cannot delete objects properly ❌
- **Buckets that had versioning then disabled:** Cannot be recovered—permanently corrupted ❌

## Suspected Problem

The versioning enable/disable toggle is not properly clearing the bucket's internal versioning state metadata. When versioning is disabled, the system should:

1. Clear all existing delete markers
2. Reset the versioning flag at the storage backend level
3. Restore normal deletion behavior

Currently, it appears that step 1 and/or step 2 are not being executed, leaving the bucket in an inconsistent state.

## Recommendation

The fix should focus on the versioning state management layer, ensuring that:
- Disabling versioning properly cleans up delete markers
- The bucket's internal state is fully reset when transitioning from enabled to disabled
- No orphaned versioning metadata remains after the transition

---

**Environment:** RustFS with `mc` (minio-client)

**Comment by loverustfs** [comment]
> Hi [@loverustfs](https://github.com/loverustfs),
> 
> I have done some testing this morning to try and help and see whats really going on, below is what ive found and hope it can help your team to fix the issues.
> 
> # Bug Fix: Versioning Control Deletion Issue
> ## Summary
> After investigating further, I believe iv'e identified the root cause of the deletion issue. The problem stems from **bucket versioning state management** rather than the deletion mechanism itself.
> 
> ## Root Cause Analysis
> ### The Issue
> When versioning control is enabled on a bucket (or has been previously enabled and then disabled), the `mc rm` command creates delete markers instead of performing actual deletions. This persists even after versioning is explicitly disabled, rendering the bucket unable to be cleaned up properly.
> 
> ### Key Finding
> The core problem is that **enabling/disabling versioning isn't properly resetting the bucket's internal state**. Once versioning is enabled, disabling it later doesn't clear the versioning markers, causing the deletion behavior to remain corrupted.
> 
> ## Evidence and Test Cases
> ### Test Case 1: Fresh Bucket (No Versioning)
> ✅ **Works correctly**
> 
> ~/minio
> ❯ mc ls rustfs-backup/testbucket/phpipam_20251116.034800/
> [2025-12-09 10:08:57 GMT]   102B STANDARD phpipam_data_20251116.tar.gz
> 
> ~/minio
> ❯ mc rm --force --recursive rustfs-backup/testbucket/phpipam_20251116.034800/
> Removed `rustfs-backup/testbucket/phpipam_20251116.034800/phpipam_data_20251116.tar.gz`.
> 
> ~/minio
> ❯ mc ls rustfs-backup/testbucket/|grep phpipam_20251116.034800/
> **Result:** Object deleted successfully. No delete markers created.
> 
> ### Test Case 2: Bucket with Versioning Enabled
> ❌ **Fails - creates delete markers**
> 
> ~/minio
> ❯ mc ls rustfs-backup/testbucket/phpipam_20251117.034800/
> [2025-12-09 10:08:57 GMT]   102B STANDARD phpipam_data_20251117.tar.gz
> 
> ~/minio
> ❯ mc rm --force --recursive rustfs-backup/testbucket/phpipam_20251117.034800/
> Created delete marker `rustfs-backup/testbucket/phpipam_20251117.034800/phpipam_data_20251117.tar.gz` (versionId=6003c1f1-6de8-41ba-91d6-bf381bbadc9a).
> 
> ~/minio
> ❯ mc ls rustfs-backup/testbucket/|grep phpipam_20251117.034800/
> [2025-12-09 10:11:54 GMT]     0B phpipam_20251117.034800/
> **Result:** Delete markers persist; directory still visible.
> 
> ### Test Case 3: Bucket with Versioning Disabled (After Being Enabled)
> ❌ **Still fails - problem persists**
> 
> ~/minio
> ❯ mc rm --force --recursive rustfs-backup/testbucket/phpipam_20251117.034800/
> Created delete marker `rustfs-backup/testbucket/phpipam_20251117.034800/phpipam_data_20251117.tar.gz`.
> 
> ~/minio
> ❯ mc ls rustfs-backup/testbucket/|grep phpipam_20251117.034800/
> [2025-12-09 10:13:04 GMT]     0B phpipam_20251117.034800/
> **Result:** Even with versioning disabled, delete markers are still created. The bucket is now permanently unable to clean up objects.
> 
> ## Impact
> * **New buckets without versioning:** Work correctly ✅
> * **Buckets with versioning enabled:** Cannot delete objects properly ❌
> * **Buckets that had versioning then disabled:** Cannot be recovered—permanently corrupted ❌
> 
> ## Suspected Problem
> The versioning enable/disable toggle is not properly clearing the bucket's internal versioning state metadata. When versioning is disabled, the system should:
> 
> 1. Clear all existing delete markers
> 2. Reset the versioning flag at the storage backend level
> 3. Restore normal deletion behavior
> 
> Currently, it appears that step 1 and/or step 2 are not being executed, leaving the bucket in an inconsistent state.
> 
> ## Recommendation
> The fix should focus on the versioning state management layer, ensuring that:
> 
> * Disabling versioning properly cleans up delete markers
> * The bucket's internal state is fully reset when transitioning from enabled to disabled
> * No orphaned versioning metadata remains after the transition
> 
> **Environment:** RustFS with `mc` (minio-client)

Wow, your test is so professional!

Thank you!

We will fix this bug based on your test.

**Comment by cxymds** [comment]
@ALL This issue has been resolved by adding a custom header to the request when deleting all versions. Please wait for the update to take effect.

**Comment by soakes** [comment]
> [@ALL](https://github.com/ALL) This issue has been resolved by adding a custom header to the request when deleting all versions. Please wait for the update to take effect.

Very well done and big thank you! @cxymds

**Comment by heihutu** [comment]
It is recommended to upgrade to RustFS version 80 or higher, as this version has fixed the version control-related deletion issue. Please wait for the update to take effect and then try deleting the empty directory; the problem should be resolved. Thank you very much for your patience and feedback!

**Comment by soakes** [comment]
Thank you for the prompt fix. I appreciate the work on resolving the version control deletion issue and will test version 80+ as soon as possible.

## Update: Compatibility Issue Preventing Validation

Unfortunately, I am currently unable to validate the fix due to a breaking change introduced in version 79. The application fails to start on Synology NAS platforms with the following error:

```
rustfs  | RustFS server version: refs/tags/1.0.0-alpha.81 started successfully at 0.0.0.0:9000, current time: 2026-01-27T21:25:59.392472842Z[Etc/Unknown]
rustfs  | getentropy failed.
```


### Technical Analysis

Synology NAS devices utilize custom Linux kernels based on significantly older upstream versions. The affected system is running kernel version `3.10.108`, which predates the introduction of the `getrandom(2)` system call.[^1][^2]

The `getentropy()` function depends on `getrandom(2)`, which was introduced in Linux kernel 3.17 (October 2014). Consequently, RustFS versions 79 and above are incompatible with Synology platforms running kernel 3.10.x.[^2][^1]

### Path Forward

I have isolated the regression to version 79+ introduction of the `getentropy` requirement. To avoid conflating issues, I will file a separate bug report specifically addressing this Synology compatibility regression.

I wanted to provide this context here to explain why I am unable to verify the version control deletion fix at this time. Once the entropy compatibility issue is resolved, I will be able to validate the original fix and provide feedback.

Thank you for your understanding and continued work on this project.

*Update*
I have just created this issue to keep this clean.

https://github.com/rustfs/rustfs/issues/1633

**Comment by heihutu** [comment]
Thank you for providing the detailed information and test results. We have fixed the version control-related deletion issue based on your feedback and added custom request headers in the latest version to handle deletion for all versions. Please try deleting the empty directory again after the update takes effect, and the issue should be resolved.


Additionally, we noticed that you encountered compatibility issues with version 79+. This is due to the outdated kernel version used by the Synology NAS platform. We have logged this issue as a separate bug report and will continue to work on resolving the compatibility issues.


Thank you again for your patience and feedback. We look forward to your further testing and feedback. If you have any other questions, please feel free to contact us.

**Comment by cruvie** [comment]
@heihutu test with RustFS server version: refs/tags/1.0.0-alpha.81 started successfully at [::]:9000, current time: 2026-01-30T05:16:21.896587545Z[Etc/Unknown]

still cannot delete empty folder and empty folder still exists after delete all objs in it (by aws-sdk-go-v2)

**Comment by yaneony** [comment]
alpha.83 still same issue.

**Comment by abrahamgreyson** [comment]
Confirm alpha.83 has the same problem. "object size" and "count" in the folder list not updated as well.

**Comment by cxymds** [comment]
> Confirm alpha.83 has the same problem. "object size" and "count" in the folder list not updated as well.

rustfs/console/pull/49  fixed.

**Comment by cxymds** [comment]
> alpha.83 still same issue.

comfirm . 
We are working for it.

**Comment by papka1974** [comment]
alpha.86 problem still there. Folder is empty. Checking to delete with all versions. All success, but folder still in place. Due to this, not possible to remove bucket.

**Comment by cxymds** [comment]
@papka1974 I tried it on version 86, and everything works fine.
Please provide your detailed reproduction steps.

https://www.loom.com/share/290596df71d143c1a11844d0374c69fe

**Comment by cruvie** [comment]
@cxymds what about using aws go sdk we mentioned above?

**Comment by cxymds** [comment]
> [@cxymds](https://github.com/cxymds) what about using aws go sdk we mentioned above?

Are you saying that you encountered the same issue when deleting using the SDK?

**Comment by cxymds** [comment]
If you are using the SDK, please add the custom header X-Rustfs-Force-Delete: true for delete all version .

**Comment by cruvie** [comment]
YES, I am the owner of this issue. I have tested it multiple times after you said it was FIXED, but the problem still persists. Could you please take a look at the discussion?

> If you are using the SDK, please add the custom header X-Rustfs-Force-Delete: true for delete all version .

version is disabled

**Comment by papka1974** [comment]
> [@papka1974](https://github.com/papka1974) I tried it on version 86, and everything works fine. Please provide your detailed reproduction steps.
> 
> https://www.loom.com/share/290596df71d143c1a11844d0374c69fe

Hi. Everything works with newly created bucket. Difference between buckets is - for problematic bucket retention is turned on. Could this be a problem? I tried to change retention settings to 1 day. Nothing. I can't turn it off.
For testing purposes, I just uploaded new file to problematic bucket with new prefix. Result was quite unexpected. Under previous folder I was not able to delete, appears all files that were there before, however I deleted them with v83 and folder was empty. Second thing - I'm not able to delete any file neither under old nor under newly created folders. Task saying success, but files still there. Also on buckets view, problematic bucket saying 1 object inside, however 2 folders there in the root.
I can provide screenshots later, but seems retention it could be retention fault.

**Comment by cxymds** [comment]
> > [@papka1974](https://github.com/papka1974) I tried it on version 86, and everything works fine. Please provide your detailed reproduction steps.
> > https://www.loom.com/share/290596df71d143c1a11844d0374c69fe
> 
> Hi. Everything works with newly created bucket. Difference between buckets is - for problematic bucket retention is turned on. Could this be a problem? I tried to change retention settings to 1 day. Nothing. I can't turn it off. For testing purposes, I just uploaded new file to problematic bucket with new prefix. Result was quite unexpected. Under previous folder I was not able to delete, appears all files that were there before, however I deleted them with v83 and folder was empty. Second thing - I'm not able to delete any file neither under old nor under newly created folders. Task saying success, but files still there. Also on buckets view, problematic bucket saying 1 object inside, however 2 folders there in the root. I can provide screenshots later, but seems retention it could be retention fault.

Confirmed that this issue exists. Thank you very much.

**Comment by papka1974** [comment]
Perfect! Finally root cause found! Waiting for the fix!

**Comment by cxymds** [comment]
> Perfect! Finally root cause found! Waiting for the fix!

I just looked up some information.This is the expected behavior of the Object Locking feature, not an error. It is designed to enforce that data cannot be deleted or overwritten for a certain period of time.

**Comment by cxymds** [comment]
> > Perfect! Finally root cause found! Waiting for the fix!
> 
> I just looked up some information.This is the expected behavior of the Object Locking feature, not an error. It is designed to enforce that data cannot be deleted or overwritten for a certain period of time.

This is to ensure data compliance and immutability. The Object Locking feature is typically used to meet strict regulatory requirements (such as SEC 17a-4(f)), which mandate that electronic records cannot be modified or deleted by any operation (including those by the root user) during the retention period.

**Comment by papka1974** [comment]
I changed retention to 1 day and still was not able to delete anything. Why so? That means that "old" retention value still stored somewhere. About newly created folder and uploaded file, that was done already with retention 1 day, so tomorrow I will check if I will be able to remove them. But still, either retention should not be editable, meaning set to N days and can't be changed anymore or change should release objects that not match it anymore.

**Comment by cxymds** [comment]
> I changed retention to 1 day and still was not able to delete anything. Why so? That means that "old" retention value still stored somewhere. About newly created folder and uploaded file, that was done already with retention 1 day, so tomorrow I will check if I will be able to remove them. But still, either retention should not be editable, meaning set to N days and can't be changed anymore or change should release objects that not match it anymore.

Got it. We’ll conduct another round of investigation.

**Comment by papka1974** [comment]
> > I changed retention to 1 day and still was not able to delete anything. Why so? That means that "old" retention value still stored somewhere. About newly created folder and uploaded file, that was done already with retention 1 day, so tomorrow I will check if I will be able to remove them. But still, either retention should not be editable, meaning set to N days and can't be changed anymore or change should release objects that not match it anymore.
> 
> Got it. We’ll conduct another round of investigation.

I will let you know tomorrow about newly created folder.

**Comment by cxymds** [comment]
> > > I changed retention to 1 day and still was not able to delete anything. Why so? That means that "old" retention value still stored somewhere. About newly created folder and uploaded file, that was done already with retention 1 day, so tomorrow I will check if I will be able to remove them. But still, either retention should not be editable, meaning set to N days and can't be changed anymore or change should release objects that not match it anymore.
> > 
> > 
> > Got it. We’ll conduct another round of investigation.
> 
> I will let you know tomorrow about newly created folder.

Okay, thank you very much.

**Comment by loverustfs** [comment]
The issue cannot be reproduced in the new version and has been fixed.

**Comment by cruvie** [comment]
NOT FIXED YET! (RUSTFS v1.0.0-alpha.88)

CANNOT DELETE FOLDER WITH AWS GO SDK!

YOU ARE NOT 100% S3 COMPATIBLITY!

WHY IGNORE MY COMMENT OVER AND OVER AGAIN?!

@loverustfs in aws S3. 

```
Deletion behavior – When you delete an object in a directory bucket, 
Amazon S3 recursively deletes any empty directories in the object path. 
For example, if you delete the object key dir1/dir2/file1.txt, Amazon S3 deletes file1.txt.
 If the dir1/ and dir2/ directories are empty and contain no other objects, Amazon S3 also deletes those directories.
```

https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-express-differences.html

**Comment by cxymds** [comment]
> NOT FIXED YET! (RUSTFS v1.0.0-alpha.88)
> 
> CANNOT DELETE FOLDER WITH AWS GO SDK!
> 
> YOU ARE NOT 100% S3 COMPATIBLITY!
> 
> WHY IGNORE MY COMMENT OVER AND OVER AGAIN?!
> 
> [@loverustfs](https://github.com/loverustfs) in aws S3.
> 
> ```
> Deletion behavior – When you delete an object in a directory bucket, 
> Amazon S3 recursively deletes any empty directories in the object path. 
> For example, if you delete the object key dir1/dir2/file1.txt, Amazon S3 deletes file1.txt.
>  If the dir1/ and dir2/ directories are empty and contain no other objects, Amazon S3 also deletes those directories.
> ```
> 
> https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-express-differences.html

hi bro , sorry for not notice your messge. please add the custom header X-Rustfs-Force-Delete: true for delete

**Comment by cruvie** [comment]
@cxymds 
1. why X-Rustfs-Force-Delete is needed? (minio need not)
2. there is no `header ` option setting in AWS GO SDK for delete op
3. s3 protocol doesn't need X-Rustfs-Force-Delete to remove empty folder after obj deleted
4. YOU ARE NOT 100% S3 COMPATIBLITY!

**Comment by cxymds** [comment]
> [@cxymds](https://github.com/cxymds)
> 
> 1. why X-Rustfs-Force-Delete is needed? (minio need not)
> 2. there is no `header ` option setting in AWS GO SDK for delete op
> 3. s3 protocol doesn't need X-Rustfs-Force-Delete to remove empty folder after obj deleted
> 4. YOU ARE NOT 100% S3 COMPATIBLITY!

This is an open-source project, and we’re continuously working to improve it. For this issue, our design is indeed different from MinIO, so the handling is also different. We’re still exploring better solutions, and this headers is our current approach. I’ll keep following up on this issue. Thanks again!

**Comment by soakes** [comment]
> [@cxymds](https://github.com/cxymds)
> 
>     1. why X-Rustfs-Force-Delete is needed? (minio need not)
> 
>     2. there is no `header ` option setting in AWS GO SDK for delete op
> 
>     3. s3 protocol doesn't need X-Rustfs-Force-Delete to remove empty folder after obj deleted
> 
>     4. YOU ARE NOT 100% S3 COMPATIBLITY!

TBH I totally agree, the RustFS README should be changed until it is 100% compatiable.

"It offers full S3 compatibility, is completely open-source, and is optimized for data lakes, AI, and big data workloads."

I have found the same issues as mentioned before in various threads. I would say RustFS has more of "Basic functionality, with the aims to become full compatibility".  While I do understand that its OSS, you still shouldn't be bending the truth on its current capabilities.  Just my two cents.

**Comment by cxymds** [comment]
@soakes 
﻿﻿
Feedback like yours is extremely valuable in helping us improve both the software and how we communicate its capabilities. Thanks again 🙏

**Comment by cruvie** [comment]
@cxymds 
I mention minio just because it's really S3 compatiable, and I leave a aws s3 doc link about the delete action for you reference.

You cannot claim that rustfs is compatible with S3 and can migrate from Minio, but in reality it is not.

I appreciate your work, but please don't fool your users and leave potential bugs to developers.

of course you can leave rustfs a simple good oss open-source product, just remove compatibility statement about minio and s3

**Comment by myrust-go** [comment]
MinIO has the same bug. You have to use` mc rm --purge `to delete it.

@cxymds @cruvie   Open source is not an obligation, so thank you for your work! Please don't let unfriendly comments get to you. Unfortunately, there will always be some rude people in the open-source community.



https://github.com/minio/minio/issues/21113
https://github.com/minio/minio/issues/18916
https://github.com/minio/minio/issues/16836

**Comment by cruvie** [comment]
@myrust-go have you ever tried with minio? minio works fine.

<img width="1916" height="722" alt="Image" src="https://github.com/user-attachments/assets/4c676f46-34f7-4e1e-a43d-0b2873b5dc18" />

<img width="1994" height="526" alt="Image" src="https://github.com/user-attachments/assets/841d6c11-5516-45ce-a207-7f0111a9d399" />

<img width="2194" height="210" alt="Image" src="https://github.com/user-attachments/assets/92b65076-bcb1-4668-8923-e139b2727a0b" />

this issue is aim to make rustfs better, you should konw open source participants also has no obligation testing rustfs, and nobody force rustfs do anything beyond their promises, please don't overreact like a child

**Comment by cxymds** [comment]
Thanks everyone — we welcome all feedback that helps improve RustFS, and we’ll continue working hard to make it better. Really appreciate all your input. Everyone has shared great insights, and we truly value all of them.

**Comment by cxymds** [comment]
> Thanks everyone — we welcome all feedback that helps improve RustFS, and we’ll continue working hard to make it better. Really appreciate all your input. Everyone has shared great insights, and we truly value all of them.

We’re currently re-evaluating this issue and exploring ways to achieve full compatibility.

**Comment by loverustfs** [comment]
- Have you enabled versioning?

- Are there steps to consistently reproduce this?

**Comment by papka1974** [comment]
I think that problems lies in inconsistency with buckets created in older versions. For me it was bucket created with version control and retention. I checked that there are no problems with newly created once (frankly don't remember, but I think even tried with retention). In my case files in prefix I would like to remove failed to delete. They disappearing (on some versions) and visually looks like no more objects, but if you check to show deleted objects they are three, then moving to newer version, these deleted objects appearing as normal, not deleted and you're not able to delete them again. Changing retention time not helping. Maybe it's possible to create kind of forced deletion, which would not check anything but just remove bucket with all associated objects/prefixes? At least temporary. Unless we're not stable. I'm not S3 expert, so don't know if this is possible, but maybe such approach would solve some bugs which already not a bugs yet.

**Comment by weisd** [comment]
@cruvie  I haven't been able to reproduce the problem you mentioned. If you created fafafa and fafafa/, please delete fafafa and fafafa/ when you delete them.

**Comment by cruvie** [comment]
> Have you enabled versioning?

NO 

@weisd I delete all old data and tried again, the problem disappeared. Perhaps some old underlying storage structures have caused this problem to persist

Thanks for you work on RUSTFS.

here is my test code

```go
package s3_test

import (
	"bytes"
	"context"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

var S3Client *s3.Client

func init() {
	cfg := aws.Config{
		Region:       "us-east-1",
		BaseEndpoint: aws.String("http://127.0.0.1:9000"),
		Credentials:  aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider("testminio", "testminio", "")),
	}
	S3Client = s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.UsePathStyle = true
	})
}

func TestUploadFileStream(t *testing.T) {
	reader := bytes.NewReader([]byte("fsdgdsgewqrewrwfsafsfsfdfsddsgdsgdsgds"))
	_, err := S3Client.PutObject(context.Background(), &s3.PutObjectInput{
		Bucket:      aws.String("ccc"),
		Key:         aws.String("fafafa/123.rrr"),
		Body:        reader,
		ContentType: aws.String("any"),
	})
	if err != nil {
		t.Fatal(err)
	}
}

func TestDeleteObject(t *testing.T) {
	_, err := S3Client.DeleteObject(context.Background(), &s3.DeleteObjectInput{
		Bucket: aws.String("ccc"),
		Key:    aws.String("fafafa/123.rrr"),
	})
	if err != nil {
		t.Fatal(err)
	}
}

```

the issue could be closed now.

**Comment by papka1974** [comment]
> [@cruvie](https://github.com/cruvie) I haven't been able to reproduce the problem you mentioned. If you created fafafa and fafafa/, please delete fafafa and fafafa/ when you delete them.

I wrote just above - ALL IS WORKING ON NEWLY CREATED BUCKETS. Needed a tool to drop old once.

**Comment by cruvie** [comment]
@papka1974 you are right!

**Comment by weisd** [comment]
we will add the purge parameter when deleting in rustfs cli to force deletion

**Comment by papka1974** [comment]
Nothing changed about this in v91.

**Comment by magicxor** [comment]
This bug seems to be fixed in v91. I'm using .NET 10 + AWS SDK to reproduce it:

```csharp
#!/usr/bin/env dotnet run
#:package AWSSDK.S3@4.*

using Amazon.S3;
using Amazon.S3.Model;
using Amazon.Runtime;

var config = new AmazonS3Config { ServiceURL = "http://localhost:9000", ForcePathStyle = true };
var s3 = new AmazonS3Client(new BasicAWSCredentials("rustfstest", "rustfspwD1297"), config);

await s3.PutBucketAsync("testbucket");

// ARRANGE
// Create directories (markers)
await s3.PutObjectAsync(new PutObjectRequest { BucketName = "testbucket", Key = "marker/" });
await s3.PutObjectAsync(new PutObjectRequest { BucketName = "testbucket", Key = "marker/subdir/" });

// Create files
await s3.PutObjectAsync(new PutObjectRequest { BucketName = "testbucket", Key = "marker/file.txt", ContentBody = "Hello, world!" });
await s3.PutObjectAsync(new PutObjectRequest { BucketName = "testbucket", Key = "marker/subdir/file.txt", ContentBody = "Hello from subdir!" });

// ACT
// 1. List all objects under prefix
var listResponse = await s3.ListObjectsV2Async(new ListObjectsV2Request { BucketName = "testbucket", Prefix = "marker/" });

Console.WriteLine($"Listed {listResponse.S3Objects.Count} objects:");
foreach (var obj in listResponse.S3Objects)
    Console.WriteLine($"  {obj.Key}");

// 2. Batch-delete all found objects
var deleteResponse = await s3.DeleteObjectsAsync(new DeleteObjectsRequest
{
    BucketName = "testbucket",
    Objects = listResponse.S3Objects.ConvertAll(o => new KeyVersion { Key = o.Key }),
});

Console.WriteLine($"Deleted: {deleteResponse.DeletedObjects.Count}, Errors: {deleteResponse.DeleteErrors?.Count ?? 0}");

// 3. Verify
var verifyResponse = await s3.ListObjectsV2Async(new ListObjectsV2Request
{
    BucketName = "testbucket",
    Prefix = "marker/",
});

if (verifyResponse.KeyCount == 0)
    Console.WriteLine("All objects (including markers) successfully deleted.");
else
{
    Console.WriteLine($"BUG: {verifyResponse.S3Objects.Count} objects remain:");
    foreach (var obj in verifyResponse.S3Objects)
        Console.WriteLine($"  {obj.Key}");
}
```

output on `rustfs/rustfs:1.0.0-alpha.86-glibc`:
```
PS C:\Users\unnamed\Downloads> dotnet run --file test-del-dir.cs
Listed 5 objects:
  marker/
  marker/file.txt
  marker/subdir/
  marker/subdir/file.txt
  marker/subdir/file.txt
Deleted: 5, Errors: 0
BUG: 1 objects remain:
  marker/
```

output on `rustfs/rustfs:1.0.0-alpha.91-glibc`:
```
PS C:\Users\unnamed\Downloads> dotnet run --file test-del-dir.cs
Listed 5 objects:
  marker/
  marker/file.txt
  marker/subdir/
  marker/subdir/file.txt
  marker/subdir/file.txt
Deleted: 5, Errors: 0
All objects (including markers) successfully deleted.
```

`ListObjectsV2` produces duplicates though. I've created an issue https://github.com/rustfs/rustfs/issues/2439

**Comment by papka1974** [comment]
You can't test this way. Problem not exist with newly created bucket. Problem appears with buckets created some time ago. Most probably with objects versioning. In my case also with retention.

**Comment by cxymds** [comment]
> You can't test this way. Problem not exist with newly created bucket. Problem appears with buckets created some time ago. Most probably with objects versioning. In my case also with retention.

At the moment, we only support the latest version. We don’t revisit issues from older versions. We’ve made many changes recently, including fixing this issue, so if it doesn’t occur in the latest version, we can consider it resolved.

**Comment by papka1974** [comment]
If you will read some posts above - single expectation right now is to get promised forced deletion. Exactly for removing such old things. And my post that nothing changed was exactly about this.
https://github.com/rustfs/rustfs/issues/768#issuecomment-4182590085

**Comment by cxymds** [comment]
> If you will read some posts above - single expectation right now is to get promised forced deletion. Exactly for removing such old things. And my post that nothing changed was exactly about this. [#768 (comment)](https://github.com/rustfs/rustfs/issues/768#issuecomment-4182590085)

I understand what you mean. What I’d like to confirm is: if a bucket is newly created in the latest version with the same configuration as before (e.g., versioning enabled and retention enabled), does this issue still occur?

**Comment by papka1974** [comment]
> > If you will read some posts above - single expectation right now is to get promised forced deletion. Exactly for removing such old things. And my post that nothing changed was exactly about this. [#768 (comment)](https://github.com/rustfs/rustfs/issues/768#issuecomment-4182590085)
> 
> I understand what you mean. What I’d like to confirm is: if a bucket is newly created in the latest version with the same configuration as before (e.g., versioning enabled and retention enabled), does this issue still occur?

Then I would ask, if this bug will be removed, will forced removal be added? As well as no one will not create new bug for next releases with the same problem and we will start all over again? I agree this bug must be closed as well as some others, but maybe not before cleanup will be possible?

**Comment by cxymds** [comment]
@papka1974 Whether to close this issue is not important—we care about whether the bug has been resolved. Since there were breaking changes in the latest version, buckets and data created in older versions may not be fully supported, so we recommend creating new ones. If newly created ones don’t have this issue, can we consider the bug resolved?

**Comment by papka1974** [comment]
> [@papka1974](https://github.com/papka1974) Whether to close this issue is not important—we care about whether the bug has been resolved. Since there were breaking changes in the latest version, buckets and data created in older versions may not be fully supported, so we recommend creating new ones. If newly created ones don’t have this issue, can we consider the bug resolved?

Approval, that all is working on newly created buckets was done already 2-3 versions ago I think.

**Comment by cruvie** [comment]
Since rustfs is still in alpha state, I agree all issue should be reproducible on latest version and if not the issue should be considered as resolved(diagnosis on old alpha version will occupy unnecessary debugging and development resources)

This issue contains several topics, any more discussion will make it more complex and hard to understand, I will close this and should be locked (it's complex enough)

Create new issues for any subsequent work and new requests pls 😊.

**Comment by TheWojtek** [comment]
> [@papka1974](https://github.com/papka1974) If newly created ones don’t have this issue, can we consider the bug resolved?

No. We do not create a new storage from scratch every time an update is issued. We update RustFS and expect it will honor the data created by the previous version. This is what I understand in "update".
Otherwise updating RustFS would not make any sense at all, because we would have to recreate the whole storage structure when a new version is out. The next version needs to be able to handle the data created by the previous version, including fixing the issues of the previous version. I find the bucket removal to be an essential feature. If it does not work on buckets created by previous versions then what, should we start building the whole object storage local infrastructure from the very beginning? In this case it is not an update but a new program (RustFS2?) incompatible with the previous program.

Source: I now sit on a 8TB bucket I can not remove.

**Comment by papka1974** [comment]
> > [@papka1974](https://github.com/papka1974) If newly created ones don’t have this issue, can we consider the bug resolved?
> 
> No. We do not create a new storage from scratch every time an update is issued. We update RustFS and expect it will honor the data created by the previous version. This is what I understand in "update". Otherwise updating RustFS would not make any sense at all, because we would have to recreate the whole storage structure when a new version is out. The next version needs to be able to handle the data created by the previous version, including fixing the issues of the previous version. I find the bucket removal to be an essential feature. If it does not work on buckets created by previous versions then what, should we start building the whole object storage local infrastructure from the very beginning? In this case it is not an update but a new program (RustFS2?) incompatible with the previous program.
> 
> Source: I now sit on a 8TB bucket I can not remove.

I fully understand you. Talking about updates - you can't expect full compatibility on alfa stage. From beta - it's a must. About this issue and some others related, since multiple tries to fix old buckets incompatibility are failed, I wrote multiple times - please add option to forced deletion of objects. IMHO this is only what is needed and will close couple of issues and will help in the future for retesting bugs. In buckets deletion issue it was promised. I though this would be added in upcoming version (91 at that moment), but nothing there. My concern on closing this issue was that no one will recall about promised. Let's see.
