### ISSUE TITLE
ListBuckets 404

### ISSUE THREAD

**Issue by jASSSSSSON** [rustfs/rustfs#976]
**Describe the bug**
After enabling virtual host mode using RUSTFS_SERVER_DOMAINS, the webui console cannot view and modify existing buckets under special configurations.

**To Reproduce**
1. use this docker env
```
      - RUSTFS_VOLUMES=/data/rustfs0
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_SERVER_DOMAINS=s3.domain.com
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=test
      - RUSTFS_SECRET_KEY=test
      - RUSTFS_LOG_LEVEL=info
```
2. Use reverse proxy。(s3.domain.com -> 9000;rustfs.dev.domain.com -> 9001)
3. Open webui

**Version**
1.0.0-alpha.70

**Expected behavior**
All is well.

**Additional context**
I have checked the logs and it seems that the webui or interface resolved the webui domain name to a virtual host, causing an error. At the same time, the default health monitoring using localhost also encountered an error. Turning off the virtual host mode has resolved the issue.
I am trying to switch minio to rustfs, and in minio, there is a special environment variable (MINIO_BROWSER_REDIRECT = https://doamin.com) You can customize the domain name of the console, which is completely separate from the API and will not interfere.

**Comment by jASSSSSSON** [comment]
The latest correction, I tried updating the version (1.0.0-alpha.70->1.0.0-alpha.71), but now there is a problem with the webui that was originally working properly with the reverse proxy. All requests will be followed by[:9001]
(like: [https://rustfs.dev.domain.com:9001/])
All environment variables remain unchanged.

**Comment by houseme** [comment]
> The latest correction, I tried updating the version (1.0.0-alpha.70->1.0.0-alpha.71), but now there is a problem with the webui that was originally working properly with the reverse proxy. All requests will be followed by[:9001] (like: [https://rustfs.dev.domain.com:9001/]) All environment variables remain unchanged.

Thank you for your feedback. Please first delete the local `1.0.0-alpha.71` image, then re-download the image. We have re-released the `1.0.0-alpha.71` image, please try updating and testing again to see if it resolves the issue you are encountering.
Also, `RUSTFS_LOG_LEVEL=info` needs to be changed to `RUSTFS_OBS_LOGGER_LEVEL=info`. If the problem still exists, please provide more detailed information so we can assist you further.

**Comment by jASSSSSSON** [comment]
Unfortunately, the problem persists. If logged in through IP, there will be no problem; In the previous version, it was possible to log in normally through reverse proxy (but there were some issues mentioned at the beginning after enabling the virtual host)
Meanwhile, as I migrated a lot of Minio's IAM, I found that when the number of policies exceeds a certain limit, the data will be folded and not all policies can be seen. There is also no page turning button or scrollbar, which seems to be a UI issue because the folded policies can be found in the associated policy section

**Comment by houseme** [comment]
https://github.com/rustfs/rustfs/issues/893

**Comment by jASSSSSSON** [comment]
I have independently reviewed solutions available in the community or on search engines, and I have attempted to adjust directory permissions, but the issue remains unresolved

**Comment by jASSSSSSON** [comment]
Regarding policies, I have confirmed that it is a WebUI issue. I can see all policies in the returned request, but there is no pagination option, and the page can only display 10 pieces of data. Should I open a separate issue?

**Comment by jASSSSSSON** [comment]
Anyway, thank you for your excellent work, which provides people with additional options. We look forward to your performance

**Comment by cxymds** [comment]
> Regarding policies, I have confirmed that it is a WebUI issue. I can see all policies in the returned request, but there is no pagination option, and the page can only display 10 pieces of data. Should I open a separate issue?

The policise list is indeed missing pagination, which has been added in the commit above

**Comment by jASSSSSSON** [comment]
Okay, received.

**Comment by loverustfs** [comment]
A fix for this has just landed in alpha.72. Could you update and give it a shot?

https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.72

If that solves it for you, go ahead and close the issue. Thanks!

**Comment by jASSSSSSON** [comment]
Hello, the issues regarding the incorrect redirect address [:9001 suffix] and the pagination of the policy page have been resolved.
However, the issue initially mentioned still persists. Apart from the absence of data on the object browsing page, all other pages are functioning normally, including the performance page where storage usage can be viewed.

**Comment by jASSSSSSON** [comment]
This is ListBuckets api return:

```
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message></Error>
```

**Comment by loverustfs** [comment]
Hey @houseme @weisd ,

I believe this PR needs to be merged.

Note:
https://github.com/rustfs/rustfs/issues/966

Code:
https://github.com/rustfs/rustfs/pull/967

**Comment by cxymds** [comment]
> This is ListBuckets api return:
> 
> ```
> <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message></Error>
> ```

got it ,We will continue to address this issue

**Comment by loverustfs** [comment]
https://github.com/rustfs/rustfs/issues/1099

Fixed. Awaiting the next version update and confirmation.

**Comment by loverustfs** [comment]
Hey  @jASSSSSSON ,

Thank you for using RustFS.

This bug has been fixed. Please upgrade to the latest version, alpha.75: https://github.com/rustfs/rustfs/releases/tag/1.0.0-alpha.75

Please verify that this resolves the issue. If the problem persists, please leave a comment below and we will reopen this issue.

**Comment by jASSSSSSON** [comment]
Hello, I have updated the latest version 1.0.0-alpha.76, but the error still exists.
For the convenience of reading, please allow me to reiterate the problem I encountered.
[s3.domain.com => rustfs:9000]
[rustfs.dev.domain.com => rustfs:9001]
At the same time, I set `RUSTFS_SERVER_DOMAINS=s3.domain.com`
Then I received an error `ListBuckets 404` on [rustfs.dev.domain.com/rustfs/console/browser]
At the same time, if RUSTFS_SERVER_DOMAINS is turned off (clearing environment variables), the management page will be functioning properly.
So I am more inclined to mistakenly identify rustfs.dev.domain.com as a storage bucket by rustfs.

**Comment by jASSSSSSON** [comment]
So unfortunately, this issue has not disappeared, please reopen it.

**Comment by loverustfs** [comment]
To the best of my knowledge, we do not support configuring two different domains on the front-end and back-end.

**Comment by loverustfs** [comment]
Reopened.

**Comment by jASSSSSSON** [comment]
I'm sorry, I hope to completely separate the API from the console, and to prevent interference, I haven't set the console as a subdomain of the API. In theory, such interference shouldn't occur

**Comment by loverustfs** [comment]
> I'm sorry, I hope to completely separate the API from the console, and to prevent interference, I haven't set the console as a subdomain of the API. In theory, such interference shouldn't occur


At present, we have no support plan.
Our focus is to ensure that the stable version is released normally.

We are going to close this issue.

**Comment by gzpan123** [comment]
> I'm sorry, I hope to completely separate the API from the console, and to prevent interference, I haven't set the console as a subdomain of the API. In theory, such interference shouldn't occur我很抱歉，我希望将 API 与控制台完全分离，为了防止干扰，我没有将控制台设置为 API 的子域名。理论上，这种情况不应该发生

try upgrade to 1.0.0-alpha.77 and set RUSTFS_SERVER_DOMAINS=s3.domain.com,rustfs.dev.domain.com

**Comment by loverustfs** [comment]
Only one domain name is supported, multiple domain names are not supported.

Use ports for separation.

@gzpan123

**Comment by loverustfs** [comment]
Hey @0xdx2 ,

Does it support multiple domains now? How do I use it?

**Comment by houseme** [comment]
Thank you for your feedback. According to your suggestion, if `RUSTFS_SERVER_DOMAINS` is set to `s3.domain.com`, the domain name for the console should be avoided as a subdomain of `s3.domain.com`. This can reduce potential interference and configuration conflicts. Please try configuring it according to this suggestion and observe if the issue is resolved. If the problem still persists, please provide more details so we can assist you further. @gzpan123

**Comment by 0xdx2** [comment]
> Hey [@0xdx2](https://github.com/0xdx2) , Hey,
>
Does it support multiple domains now? How do I use it?

This works: `RUSTFS_SERVER_DOMAINS=s3.domain.com,rustfs.dev.domain.com`. Now we'll try matching all of these. However, if you are using a specific port, you need to include the port number; otherwise, the vhost mode domain will not be recognized.
